### ISSUE TITLE
Providing multiple times the same device ends with multiple events of subscription.

### ISSUE THREAD

**Issue by ezequiel-umu** [telefonicaid/iotagent-json#101]
I have a device which subscribes to configuration value "luminosidad", but each time I deploy new software, I restart the IoTA MQTT (which is configured to memory instead of mongodb), I do the device provide again, and each time I do this I end up with more and more messages in Mosquitto topic /1234/MQTT/configuration/values:

```
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120928Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120929Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120929Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120929Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120929Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120929Z"}
{"Boton":" ","luminosidad":"40","prueba":"15","dt":"20160311T120929Z"}
```

This got triggered by a single change in Context Broker. It looks like each time the IoTA is restarted, it does subscribe to those values again, but it doesn't clear the subscriptions done before. 

Is it intended? Is there a quick fix? I've not subscribed to Boton neither to prueba. Why do I get those?

**Comment by dmoranj** [comment]
We could see that as a consecuence of the design. The in-memory store is
designed for quick testing and thus it is not supposed to be used once and
again against a single context broker, unless a careful clean is performed
before shutting the IOTA down. I would suggest, if you are going to reuse
the devices, to activate the MongoDB repository.

**Comment by ezequiel-umu** [comment]
Then I suggest to change default configuration to use mongodb as in:

https://github.com/telefonicaid/lightweightm2m-iotagent/blob/master/config.js

which doesn't cause this behaviour.

Thank you.
