### ISSUE TITLE
SSL/TLS Encryption

### ISSUE THREAD

**Issue by drasko** [telefonicaid/iotagent-json#102]
Hello,
are there any examples how to send/recieve SSL/TLS encrypted messages?

Is this supported by IOTA-MQTT?

**Comment by dmoranj** [comment]
Do you mean sending them to the northbound or to the southbound? In the former case, we usually use an nginx for SSL termination. In the later, the security measures should be taken between the device and the MQTT broker, as that piece of middleware is usually installed along the IoT Platform. Security between the MQTT broker and the IOTA can also be configured, but we have only tested basic user and password authentication scenarios.
