### ISSUE TITLE
Push the repo to official Fiware DockerHub

### ISSUE THREAD

**Issue by drasko** [telefonicaid/iotagent-json#104]
Can you please push the repo to the official Fiware DockerHub: https://hub.docker.com/u/fiware/.

While we can find LWM2M agent (https://hub.docker.com/r/fiware/lightweightm2m-iotagent/), MQTT agent is still missing.

**Comment by dmoranj** [comment]
I'll test the dockers are running correctly and push them to DockerHub.

**Comment by dmoranj** [comment]
Done.

https://hub.docker.com/r/fiware/iotagent-mqtt/

I'll try to test it and add some examples along the week.
