### ISSUE TITLE
How to send commands to devices?

### ISSUE THREAD

**Issue by drasko** [telefonicaid/iotagent-json#108]
Hello,
what is the way to send commands or attribute updates to devices?

For example, user sets temp to 24 degrees via UI app, and this information must be propagated to the MQTT-connected actuator.

is there something like `/1234/actuator01/commands` or should we use SUB on `/1234/actuator01/attributes`?

If I understand well `mosquitto_pub -t /1234/sensor01/configuration/commands -m '{ "type": "configuration", "fields": [ "sleepTime" ] }'` is the way to send command IOTA -> Orion, but what is the correct way to send the command IOTA -> physical_device?

**Comment by dmoranj** [comment]
The way to send commands is the usual for the IoTAs, and have been recently implemented [here](https://github.com/telefonicaid/iotagent-json/pull/119). Check out the documentation for details.
