### ISSUE TITLE
allow use mongo devices instead in memory

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#144]
Default conf is in memory:
https://github.com/telefonicaid/iotagent-json/blob/develop/config.js#L42

but a docker-compose with mongo vars still starts in memory:
 - IOTA_MONGO_HOST=mongo
    - IOTA_CB_HOST=orion
    - IOTA_IOTAM_HOST=iotacpp
    - IOTA_IOTAM_PORT=8081
    - IOTA_IOTAM_PATH=/protocols
    - IOTA_IOTAM_PROTOCOL=PDI-IoTA-JSON-Node
    - IOTA_IOTAM_DESCRIPTION="JSON IoT Agent (Node.js version)"
    - IOTA_PROVIDER_URL=http://172.17.0.1:4052
    - IOTA_NORTH_PORT=4052
    - IOTA_MQTT_HOST=mosquitto
    - IOTA_MQTT_PORT=1883
    - IOTA_LOG_LEVEL=DEBUG
iota-mqtt_1    | time=2016-06-03T10:29:02.636Z | lvl=ERROR | corr=765b9aa4-8350-4ba7-b0d6-e1d0d7d963b6 | trans=765b9aa4-8350-4ba7-b0d6-e1d0d7d963b6 | op=IoTAgentNGSI.InMemoryGroupRegister |

**Comment by dmoranj** [comment]
This problem can be fixed using IOTA_REGISTRY_TYPE environment variable.
