### ISSUE TITLE
No host found for MongoDB driver.

### ISSUE THREAD

**Issue by lilezek** [telefonicaid/iotagent-json#155]
```time=2016-06-21T10:34:14.895Z | lvl=FATAL | corr=a29b76f6-88ed-4ac3-9570-0409289a620c | trans=a29b76f6-88ed-4ac3-9570-0409289a620c | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=No host found for MongoDB driver.```

With this configuration inside config.iota:

```
deviceRegistry: {
        type: 'mongodb',
        host: 'localhost'
    }
```

And MongoDB running in localhost without password. Other IoTAgents (like CoAP) are working with this  configuration. 

Any ideas?

**Comment by lilezek** [comment]
It seems to have been forgotten to update config.js. 

*If anyone is having any problem setting up configuration of this Agent just check this file:*

https://github.com/telefonicaid/iotagent-ul/blob/master/config.js

**Comment by dmoranj** [comment]
You're right, last updated example config file is present in the UL IoT Agent. There is an issue to add a similarly commented config file for the JSON IoTA as well: #120.
