### ISSUE TITLE
Missing changelog in the RPM Spec

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-json#177]
The RPM spec did not have any changelog until the 1.2 version. In that version, the changes from the version itself were introduced, but the past changes were not. These should be completed to have a complete changelog of the product in the RPM.

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/iotagent-json/blob/06e77950f67dba4aa1b03d073ec318029e35ccfa/rpm/SPECS/iotajson.spec#L171-L173
