### ISSUE TITLE
Documentation issue in fiware-iot-stack

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-json#183]
In section "Send measures using JSON HTTP" in http://fiware-iot-stack.readthedocs.io/en/release-v4.0/device_api/index.html#send-observations  is stated that the url is /iot/d when the corret url is /iot/json

Just a small copy/paste issue ;-)

**Comment by dmoranj** [comment]
Fixed [here](https://github.com/telefonicaid/fiware-iot-stack/pull/40)
