### ISSUE TITLE
Pool command expired but CB not updated

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-json#199]
When a poll command is expired (the device has not requested the command within the valid period) the CB is not updated accordingly. Iotagent should update CB with command_status ERROR and command_info with a descriptive error message.

**Comment by dmoranj** [comment]
This bug doesn't belong here, but in the library. I created a [new issue](https://github.com/telefonicaid/iotagent-node-lib/pull/510) in the library.
