### ISSUE TITLE
Improvements for the documentation

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-json#216]
- Change the documentation to make it agnostic of the transport (the IoTAgent is mentioned a few times as MQTT-JSON).
- Missing HTTP transport description in installation guide (MQTT section is present). 
- Change the subtopic order in the HTTP description (Data, Commands, Configuration), as it differs from MQTT (Data, Configuraiton, Commands).
- The link https://github.com/telefonicaid/iotagent-json/blob/master/README#protocol is broken.
- https://github.com/telefonicaid/iotagent-json/blob/master/README.md#configuration has an anchor broken
- Some typos: unidirectionsl, aboveg, sepparate, gorup 
- "NGSI10/" should be changed to "/v1".
- Required Orion version should be a bit higher (as current IoTAgents are being tested with superior versions).

**Comment by fgalan** [comment]
@taliaga which are the "5 items" you mention at https://github.com/telefonicaid/iotagent-json/pull/245 were solved, pls?

**Comment by taliaga** [comment]
4th, 5th, 6th and 7th. For the 8th I decided to take no action as discussed in the PR. The new list would be:

- Change the documentation to make it agnostic of the transport (the IoTAgent is mentioned a few times as MQTT-JSON).
- Missing HTTP transport description in installation guide (MQTT section is present).
- Change the subtopic order in the HTTP description (Data, Commands, Configuration), as it differs from MQTT (Data, Configuraiton, Commands).
- Required Orion version should be a bit higher (as current IoTAgents are being tested with superior versions).

**Comment by fgalan** [comment]
@taliaga thanks for your cleanup effort on documentation! New contributions to this issue are really welcomed :)

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-json/pull/410 improves documentation.

Not sure if this fully covers the issue, but the documentation has changed quite a bit since 17 Jan 2017 :) so I think it's better to close this old issue and, if needed, open new ones with problems in the current documentation.
