### ISSUE TITLE
Step-by-step guide not working

### ISSUE THREAD

**Issue by vears91** [telefonicaid/iotagent-json#222]
Following the steps in the guide I get the following error when attempting to publish to the topic, after provisioning the device with the API

> time=2017-03-24T11:50:10.305Z | lvl=ERROR | corr=fbbbf3bc-bf3b-40a8-8d2d-e58f933c07e2 | trans=fbbbf3bc-bf3b-40a8-8d2d-e58f933c07e2 | op=IoTAgentJSON.MQTTBinding | srv=n/a | subsrv=n/a | msg=MEASURES-004: Device not found for topic [/1234/sensor01/attrs] | comp=IoTAgent

**Comment by Naff16** [comment]
Im having the same problem, the values of temperature and luminosity are always empty. They not update when i execute: mosquitto_pub -t "/1234/sensor01/attrs" -m '{"l":4,"t": "31.5"}'.

**Comment by vears91** [comment]
The steps in the  "Provisioning multiple devices with a Configuration" section do work for me. The steps in "Provisioning a single device with the default API Key" didn't.

**Comment by Naff16** [comment]
Yes it worked the same for me, im only having  problems at 'Provisioning a single device with the default API Key'

**Comment by Naff16** [comment]
In config.js file, if you remove from config.mqtt.defaultKey: '1234' and put it in config.iota.defaultKey: '1234' it will solve the problem, now i can send measures and update the device.

**Comment by fgalan** [comment]
@vear91, if you confirm the solution, please close the issue. Thanks!

**Comment by fgalan** [comment]
This issue seems to be related with https://github.com/telefonicaid/iotagent-json/issues/207 (maybe a duplicate?)

**Comment by taliaga** [comment]
I've faced the same problem when trying to follow the step-by-step and also had to move the defaultKey configuration from the mqtt to the iota configuration sections to make the first step work.  I tend to believe it's plausible for now to fix the default config.js to stop people from attempting their first steps. 

However, I would like to better understand why this happens. A difference I've noticed in the logs of the agent with this change is that when the "defaultKey" is not in the iota section it looks there's a fallback to transport:HTTP somewhere in the chaining of agent-device. I'm afraid I'm totally new to IoTAgents and haven't yet understood the overall implementation idea so I'm still not able to offer a better suggestion :/

**Comment by taliaga** [comment]
@Naff16 could you share the config file you used to successfully update the device?

**Comment by fgalan** [comment]
The problem described in this issue has been supposedly fixed by PR https://github.com/telefonicaid/iotagent-json/pull/260, recently merged into master.

@Naff16, @taliaga , @vears91  could you check if now it is ok, pls?

**Comment by galorene** [comment]
Hi,
I am following the guide "Step by step", in the part of "Sending measures with the device" when I publish the information to the Context Broker the values always return me null. I have tried to do it from "Provisioning a single device with the default API Key" and "Provisioning multiple devices with a Configuration", in both the same thing happens, the null value.

**Comment by fgalan** [comment]
@galorene in order to clearly understand the issue and eventually debug/solve it, could you add in a comment in the present issue which particular request are you using to send measures and the response you get, please? Thx!

**Comment by galorene** [comment]
Well, i 've got the dockers in differents hosts. 

-Orion private ip: 10.0.15.5
-MongoDB private ip: 10.0.15.30
-IotAgent and mosquitto are on the same host.

I have been using this commands from the guide changing the service and subservice:

**Command to create the dispositive:**

curl -X POST -H "Fiware-Service: howtoService" -H "Fiware-ServicePath: /howto" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{ 
    "devices": [ 
        { 
            "device_id": "sensor01", 
            "entity_name": "LivingRoomSensor", 
            "entity_type": "multiSensor", 
            "attributes": [ 
                  { "object_id": "t", "name": "Temperature", "type": "celsius" },
                  { "object_id": "l", "name": "Luminosity", "type": "lumens" }                  
            ]
        }
    ]
}
' 'http://localhost:4041/iot/devices'

**Command to change the values:**
mosquitto_pub -t /1234/sensor01/attrs -m '{"l":4,"t": "31.5"}'

**Command to post the information on Context Orion:**

curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Fiware-Service: howtoService" -H "Fiware-ServicePath: /howto" -d '{
    "entities": [
        {
            "isPattern": "false",
            "id": "LivingRoomSensor",
            "type": "multiSensor"
        }
    ]
}' 'http://10.0.15.5:1026/v1/queryContext'

**And this is what i get:**
{"contextResponses":[{"contextElement":{"type":"multiSensor","isPattern":"false","id":"LivingRoomSensor","attributes":[{"name":"Luminosity","type":"lumens","value":" "},{"name":"Temperature","type":"celsius","value":" "},{"name":"TimeInstant","type":"ISO8601","value":" "}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]}

**The config file:** https://gist.github.com/galorene/05f03af6d3c8699acef574d4ff7d3236

Notes: This is from **Provisioning a single device with the default API Key**, I've tried the **Provisioning multiple devices with a Configuration** too but i get the same response. I tried do it on local too, but the same happened.

Thanks for respond!

**Comment by fgalan** [comment]
Could you add the traces at IOTAgent when mosquitto_pub and POST /v1/queryContext are executed, please? Use separte comments for each one.

**Comment by galorene** [comment]
I'm not sure if is this what you want... Please if I'm wrong, tell me the command that i should use.

mosquitto_pub -t /1234/sensor01/attrs -m '{"l":4,"t": "31.5"}' -d
Client mosqpub|8114-FiwooFiwar sending CONNECT
Client mosqpub|8114-FiwooFiwar received CONNACK
Client mosqpub|8114-FiwooFiwar sending PUBLISH (d0, q0, r0, m1, '/1234/sensor01/attrs', ... (19 bytes))
Client mosqpub|8114-FiwooFiwar sending DISCONNECT

**Comment by fgalan** [comment]
That is the mosquitto pub debug trace. What I mean is the log of the IoTAgent component. 

If IOTAgent is running inside docker, I think `docker log` or `docker logs` (not remembering right now the exact syntax) will show it.

**Comment by galorene** [comment]
I have already solved the problem I had, the changes I make are already saved in the POST. Thanks for the help.
