### ISSUE TITLE
Retrieving configuration parameters from the Context Broker

### ISSUE THREAD

**Issue by Naff16** [telefonicaid/iotagent-json#223]
When i execute the curl:
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Fiware-Service: myHome" -H "Fiware-ServicePath: /environment" -H "Cache-Control: no-cache" -d '{
"value" : "300"
}' 'http://localhost:1026/v1/contextEntities/LivingRoomSensor/attrs/sleepTime'

Response:

{
  "orionError" : {
    "code" : "400",
    "reasonPhrase" : "Bad Request",
    "details" : "service not found"
  }
}
How to fix this???

Cumps

**Comment by fgalan** [comment]
This question is not actually related with IOTAgents, but with Orion Context Broker.

Would you be so kind of asking it at StackOverflow (http://stackoverflow.com) using the "fiware-orion" labe, please? Then, include the link to the question in this issue thread and close it.

Thanks!
