### ISSUE TITLE
sleepTime Value Error

### ISSUE THREAD

**Issue by Naff16** [telefonicaid/iotagent-json#224]
While doing: 
mosquitto_pub -t /1234/sensor01/configuration/commands -m '{ "type": "configuration", "fields": [ "sleepTime" ] }'  the response should be something like this: {"sleepTime":"300","dt":"20160209T111442Z"}.

But nothing is happening, it is giving some errors at the server window:
...
Couldn't get the requested values from the Context Broker: [object Object] | comp=IoTAgent
...
Any solution?

**Comment by Chandradeep-NEC** [comment]
@Naff16  @fgalan 
Please confirm as if no one is working on this issue.
We have done some investigation on this.

**Comment by fgalan** [comment]
As far as I know, nobody is working on this.

CC: @AlvaroVega

**Comment by DeepshikhaNEC** [comment]
@fgalan @Naff16 @AlvaroVega  Hi,

As per my investigation there are two use cases to retrieve  configuration parameters from the context broker as follows :

case 1:  HTTP Transport: 
If there is no transport key is submitted at the time of device provisioning then "HTTP" will be set as default transport. In this case it requires a device endpoint key which must be given at the time of device provisioning .
Device receives the requested configuration keys at /configuration route of device endpoint.

case 2: MQTT Transport:
If device provisioned using MQTT as transport key, The context broker publishes the configuration values at topic /configuration/values. The MQTT device subscribes the same topic , hence receives the configuration values. In this case it doesn't require any device endpoint key.

In this issue , the case 1 is occurring while registering the device using provisioning API. The Agent sets the default transport i.e. HTTP for the device. As we can see, the request is of MQTT type but the context broker tries to send the values on HTTP transport ( default ) thats why user is unable to get the values at subscribed topic. Results in the Error “Device Endpoint not found”.

To fix this, we can do following
1.	Register the device with HTTP transport along with the ENDPOINT of the device , which will be used by context broker to send the values to device. Device must support HTTP transport.
![deviceRegistration-HTTPRequest](https://user-images.githubusercontent.com/62232111/86751169-1c260780-c05c-11ea-8da7-13822ec2703f.PNG)

![DeviceRegistered-HTTP](https://user-images.githubusercontent.com/62232111/86751206-20eabb80-c05c-11ea-9415-2c1f1dc449b0.PNG)

2.	Register the device with MQTT transport. Later on , one can subscribe the topic and get the published values from context broker on same topic.
![deviceRegistration-MQTTRequest](https://user-images.githubusercontent.com/62232111/86751312-33fd8b80-c05c-11ea-978a-cfba809ba377.png)

![deviceRegistered-MQTT](https://user-images.githubusercontent.com/62232111/86751340-37911280-c05c-11ea-883a-eab4707f8abd.PNG)


Suggestion :
The documentation don’t specify transport information in retrieval process which plays very important role. Hence we should update it in such a manner , the user can understand the different cases to get the information as per their need.

**Comment by fgalan** [comment]
Not fully sure of understanding the full point :) but if I read your conclusions:

>  The documentation don’t specify transport information in retrieval process which plays very important role. Hence we should update it in such a manner , the user can understand the different cases to get the information as per their need.

I understand this issue would be fixed improving documentation. Is my interpretation correct?

On the other hand, what about the trace shown in the issue body?

```
 Couldn't get the requested values from the Context Broker: [object Object] | comp=IoTAgent
```

Should be fixed to show an actual helpful message instead of that opaque `[object Object]`. What do you think?

**Comment by DeepshikhaNEC** [comment]
> Not fully sure of understanding the full point :) but if I read your conclusions:
> 
> > The documentation don’t specify transport information in retrieval process which plays very important role. Hence we should update it in such a manner , the user can understand the different cases to get the information as per their need.
> 
> I understand this issue would be fixed improving documentation. Is my interpretation correct?
> 
> On the other hand, what about the trace shown in the issue body?
> 
> ```
>  Couldn't get the requested values from the Context Broker: [object Object] | comp=IoTAgent
> ```
> 
> Should be fixed to show an actual helpful message instead of that opaque `[object Object]`. What do you think?

@fgalan Hi, Yes we have to update the document specifying  MQTT transport key in the JSON body of device provisioning api request. And this case will be applicable only for MQTT based devices.

For logging we need to update the source code for detailed messages log.

**Comment by fgalan** [comment]
> @fgalan Hi, Yes we have to update the document specifying MQTT transport key in the JSON body of device provisioning api request. And this case will be applicable only for MQTT based devices.
>
> For logging we need to update the source code for detailed messages log.

So I understand you are going to create a pull request with these changes? After that, we would review it and provide feedback.

Thanks!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/482
