### ISSUE TITLE
MongoDB driver bug (NODE-818)

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/iotagent-json#226]
MongoDB driver for Node.js shows a bug related to replica set discovery process. In more details, if some node on the replica set time outs before the discovery finishes, the driver returns "no primary found". Please check the issue [NODE-818](https://jira.mongodb.org/browse/NODE-818) at MongoDB's Jira.

Such an error is fixed in MongoDB driver for Node.js version 2.2.10. Neverhteless, this agent uses version 2.1.19.

**Comment by fgalan** [comment]
"Parent" issue: https://github.com/telefonicaid/iotagent-node-lib/issues/545

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-json/pull/229
