### ISSUE TITLE
ERROR: CAN'T CREATE A SERVICE 

### ISSUE THREAD

**Issue by fermenreq** [telefonicaid/iotagent-json#231]
Hi all, 

I have a problem in order to create this: [here.](https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md#provisioning-the-device)  

It shows the following erros:

- In IoTA terminal:
`time=2017-02-14T15:06:14.832Z | lvl=ERROR | corr=88ed3729-6682-44ce-9b0a-28098e54c94e | trans=88ed3729-6682-44ce-9b0a-28098e54c94e | op=IoTAgentNGSI.DomainControl | srv=myHome | subsrv=/environment | msg=TypeError: Cannot read property 'findOne' of undefined | comp=IoTAgent`

- In "cURL terminal":
`curl: (52) Empty reply from server`

I donwloaded and setting an IotAgent, particulary JSON iot Agent: [iotAgent JSON](https://github.com/Fiware/iot.IoTagent-JSON)

- Here is my iotAgent settings:

```
{
"logLevel": "DEBUG",
"timestamp": true,
"contextBroker": {
    "host": "localhost",
    "port": "1026"
},
"server": {
    "port": 4041,
    "host": "localhost"
},
"deviceRegistry": {
    "type": "mongodb"
},
"mongodb": {
    "host": "172.17.0.2",
    "port": "27017",
    "db": "iotagentjson"
},
"types": {},
"service": "myHome",
"subservice": "/environment",
"providerUrl": "http://************:4041",
"deviceRegistrationDuration": "P1M",
"defaultType": "Thing",
"iotaVersion": "1.5.0-next"
}
```
```
-Orion Context Broker Version
{
"orion" : {
  "version" : "1.7.0-next",
  "uptime" : "1 d, 2 h, 24 m, 7 s",
  "git_hash" : "92680df41fe0d1cc22fb588613029d2e1b8eb230",
  "compile_time" : "Fri Jul 14 11:20:52 UTC 2017",
  "compiled_by" : "root",
  "compiled_in" : "b99744612d0b"
}
}
```
**Note: Orion Context Broker was installed using his docker image.** 

I'm using a Centos 7 Machine in a Fiware Cloud site. 

When I send a HTTP POST request
```
POST http://**************:4041/iot/services/
Content-Type:application/json
X-Auth-Token:*****************************
Fiware-Service:myHome
Fiware-ServicePath:/environment

{
  "services": [
    {
      "apikey":      "",
      "cbroker":     "http://orion context broker :1026",
      "entity_type": "thing",
      "resource":    "/iot/d"
    }
  ]
}
```

It return a 500 internal server error like this:

```
{
"name": "TypeError",
"message": "Cannot read property 'findOne' of undefined"
}
```

 I dont have **Fiware-Service:myHome** and **Fiware-ServicePath:/environment** created. So my question is how can I create it ? I was reading the following guides: 

[http://docs.telefonicaiotiotagents.apiary.io/#reference/configuration-api/services/create-a-service](http://docs.telefonicaiotiotagents.apiary.io/#reference/configuration-api/services/create-a-service )

[http://fiwaretourguide.readthedocs.io/en/latest/connection-to-the-internet-of-things/how-to-read-measures-captured-from-iot-devices](http://fiwaretourguide.readthedocs.io/en/latest/connection-to-the-internet-of-things/how-to-read-measures-captured-from-iot-devices/) 

But I cant create any service

Best Regards

**Comment by TheNextLVL** [comment]
Hi fermenreq,
I have the same issue, ¿do you found the cause of the error?

**Comment by fgalan** [comment]
@TheNextLVL the issue comments show that @fermenreq closed the issue on August 28th, 2017. There isn't any comment about why it was closed, but typical reasons are that the bug was solved in the code or that, after a closer examination, it was not an actual bug.

I hop @fermenreq could clarify.

**Comment by fermenreq** [comment]
@fgalan closed cause is related to https://github.com/telefonicaid/iotagent-json/issues/230. 

@TheNextLVL make sure you are using the requirements and  a correct version of the related components. 

Thanks !

**Comment by TheNextLVL** [comment]
sorry, I have the issue but, with iotagent-ul. I'll take a look at #230  anyway.
Thank you very much to both.

**Comment by fgalan** [comment]
@TheNextLVL if the problem confirms, maybe it would be a good idea to open a new & fresh issue with the report of your problem.
