### ISSUE TITLE
typo in logger level of ApiKey configuration

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#247]
https://github.com/telefonicaid/iotagent-json/blob/master/lib/iotaUtils.js#L52

```
        } else {
            config.getLogger().ierror(context, 'Could not find any API Key information for device.');
            callback(new errors.GroupNotFound(service, subservice));
}

```

an unexpected behaviour is (not error is trace is printed...)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/246
