### ISSUE TITLE
Unit tests are not passed with Node.js 8.x

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-json#267]
Using v8.7.0, the results are:

```
  9 passing (28s)
  3 pending
  59 failing

```

**Comment by fgalan** [comment]
I understand PR https://github.com/telefonicaid/iotagent-json/pull/339 probes that test are now working for Node v8 so this issue  can be closed, isn't it?

**Comment by dcalvoalonso** [comment]
You're more than right! Closing it!
