### ISSUE TITLE
Problem with updating the Context from IotAgent

### ISSUE THREAD

**Issue by mausquirk** [telefonicaid/iotagent-json#275]
In our current setup, there is a problem with context updates from iotagent to the context broker (CB):

iotAgent reports (full [iota-problem.log](https://github.com/telefonicaid/iotagent-json/files/1797256/iota-problem.log)):
 
     "No context element found",
     "details": "TrafficSensor:TrafficSensor01"

Checking Orion's mongodb ([Mongodb-content.txt](https://github.com/telefonicaid/iotagent-json/files/1797260/Mongodb-content.txt)) the context ID seems to exist.

You also find the iota configuration file [config.txt](https://github.com/telefonicaid/iotagent-json/files/1797259/config.txt) to this issue.

Why does the iotagent receive a 404-Error about the non-existing element? Thought the element does exist,

Let me know in case you need additional log extracts or information about our current configuration.

**Comment by fgalan** [comment]
Hint: moving the .log and .txt file to https://gist.github.com/ links would make them more accesible. Thanks!

**Comment by mausquirk** [comment]
Thanks for the hint: I have put the files on gist:
https://gist.github.com/mausquirk/43acc9191e4b28886f918bbb048929c5

**Comment by fermenreq** [comment]
Please @mausquirk , 

It's seem better if you provide more details about configuration settings, script context updates and installation process and running. 

A good way is to start it using docker compose to run mongoDB and Fiware OCB. I’m using the following version:
-	Image: Mongo 3.2
-	Image: Fiware/orion image
-	Mosquitto 1.4.8
 
Mandatory Steps:
 
-	1st        Up the services before using docker-compose 
-	2nd       Copy IP address containers (mongo & Orion) to IotAgent config.js file. It allow to have a connection between the agent to both services.
  Set up the Apikey input, that allow a connection between the service and the device. 
-	3rd        Execute the IotAgent : iotagent/bin config.js 
-	4th        Create a device (see script)
-	5th        Create a service: (see script)
-	6th        Send measures.(see script). You can use http commands or using Mosquitto.
-	To see if it works, request to OCB. (see script)

## 1 Create a device:
``` 
curl -X POST -H "Fiware-Service: myHome" -H "Fiware-ServicePath: /environment" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
     "devices": [
         {
             "device_id": "sensor03",
             "entity_name": "LivingRoomSensor",
             "entity_type": "multiSensor",
             "attributes": [
                   { "object_id": "t", "name": "Temperature", "type": "celsius" },
                   { "object_id": "c", "name": "Luminosity", "type": "string" }
             ],
                 "commands": [
                                   { "object_id": "l", "name": "setOn", "type": "string", "value":"OFF" }
                        ]
         }
     ]
}' 'http://localhost:4061/iot/devices'  
 ```

## 2 Create a service:
 
```
curl -X POST -H "Fiware-Service: myHome" -H "Fiware-ServicePath: /environment" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
"services": [
            {
          "resource": "/",
          "apikey": "TEF",
          "type": "multiSensor",
          "cbroker":"172.18.0.3:1026"
            }
            ]
}' 'http://localhost:4061/iot/services'
```
 
## 3 Send Measures:
 ```
mosquitto_pub -t /TEF/sensor03/attrs -m 't|35|c|yellow
 ```
## 4 Ask OCB for new updates:
 ```
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Fiware-Service: myHome" -H "Fiware-ServicePath: /environment" -d '{
    "entities": [
        {
            "isPattern": "false",
            "id": "LivingRoomSensor",
            "type": "multiSensor"
        }
    ]
}' 'http://172.18.0.3:1026/NGSI10/queryContext'
 ```
 
I hope help you.
 
Thanks 
Fernando.

**Comment by mausquirk** [comment]
> please create the device before the service 
How can I delete any existing service on the iotAgent-API?

**Comment by fermenreq** [comment]
Hi @mausquirk ,

There have been many changes with OCB version, please see the documentation above. 
https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md#prerequisites

For your question please see the IoTAgent API: https://telefonicaiotiotagents.docs.apiary.io/#reference/configuration-api/services/remove-a-subservice/service

Thanks,
Fernando

**Comment by mausquirk** [comment]
Hi @fermenreq,

Thanks for your support. I currently try 
- to retrieve a list of services from iota (https://telefonicaiotiotagents.docs.apiary.io/#reference/configuration-api/services/retrieve-a-service) 
- delete a service on iota in order to obey the creation order (device first, service second).

I badly fail with both actions attempts:

### retrieve services
Request:
`curl -i  --header "Content-Type: application/json" --header "Fiware-Service: winterthur_traffic"      --header "Fiware-ServicePath: /*"   'http://orion.acousticity.io:4041/services?apikey=2907204D' `

Response:
```
curl -i --header "Content-Type: application/json" --header "Fiware-Service: winterthur_traffic" --header "Fiware-ServicePath: /*" 'http://orion.acousticity.io:4041/services'
HTTP/1.1 404 Not Found
X-Powered-By: Express
Fiware-Correlator: 5781cf0c-2875-4a85-b76c-d28300fb7ad0
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 147
Date: Fri, 01 Jun 2018 12:13:50 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /services</pre>
</body>
</html>
```
It cannot understand the error response `cannot GET /services`. [API-Documentation](https://telefonicaiotiotagents.docs.apiary.io/#reference/configuration-api/services/retrieve-a-service) indicates a GET-Request. 

*iota reports*
```
iotagent_1           | time=2018-06-01T12:25:16.096Z | lvl=DEBUG | corr=a224081d-4948-497e-9e72-2eb484bfde16 | trans=a224081d-4948-497e-9e72-2eb484bfde16 | op=IoTAgentNGSI.DomainControl | srv=winterthur_traffic | subsrv=/* | msg=response-time: 9 | comp=IoTAgent
iotagent_1           | time=2018-06-01T12:25:26.678Z | lvl=DEBUG | corr=74eb0c0e-1a67-42c1-83b0-cbd73d72ffdb | trans=74eb0c0e-1a67-42c1-83b0-cbd73d72ffdb | op=IoTAgentNGSI.GenericMiddlewares | srv=winterthur_traffic | subsrv=/* | msg=Request for path [/services] from [orion.acousticity.io:4041] | comp=IoTAgent
iotagent_1           | time=2018-06-01T12:25:26.681Z | lvl=DEBUG | corr=74eb0c0e-1a67-42c1-83b0-cbd73d72ffdb | trans=74eb0c0e-1a67-42c1-83b0-cbd73d72ffdb | op=IoTAgentNGSI.DomainControl | srv=winterthur_traffic | subsrv=/* | msg=response-time: 4 | comp=IoTAgent
``` 
Our current config.js: 
``` 
var config = {};

config.mqtt = {
    host: 'localhost',
    port: 1883,
    defaultKey: '1234',
    thinkingThingsPlugin: true
};

config.iota = {
    logLevel: 'DEBUG',
    timestamp: true,
    contextBroker: {
        host: 'localhost',
        port: '1026'
    },
    server: {
        port: 4041
    },
    deviceRegistry: {
        type: 'mongodb'
    },
    mongodb: {
        host: 'localhost',
        port: '27017',
        db: 'iotagentjson'
    },
    types: {},
    service: 'howtoService',
    subservice: '/howto',
    providerUrl: 'http://localhost:4041',
    deviceRegistrationDuration: 'P1M',
    defaultType: 'Thing'
};

config.configRetrieval = false;

config.http = {
    port: 7896
};

module.exports = config;
```
Something wrong with that? 
Do the keys  `service` and `subservice` to be adapted to the used example data (Service: winterthur_traffic and subservice: /Zuerichstrasse)?

So if I cant retrieve/list any services, I bet I can't delete them too. It seems that there is something fundamental wrong with my setup or with the way I use iota.

**Comment by fermenreq** [comment]
Hi @mausquirk ,

Please use this issue (#275) for your news.  I see your email and I found some mistakes:
Firstly, in your ``config.js`` IotAgent file I cant see your ``config.defaultKey = '';`` field, neigther
``config.defaultTransport = 'MQTT';``. 

The defaultKey allow you to assign your device to the entity  in order to speak between them. This could be the reason that you obtain an 404 error

As I see in the **retrieve servicies** request above: 
```
Request:
curl -i --header "Content-Type: application/json" --header "Fiware-Service: winterthur_traffic" --header "Fiware-ServicePath: /*" 'http://orion.acousticity.io:4041/services?apikey=2907204D'

```
The **apikey** must be define in ```config.js``` file: See bellow

```
/*
 * Copyright 2015 Telefonica Investigación y Desarrollo, S.A.U
 *
 * This file is part of iotagent-json
 *
 * iotagent-json is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * iotagent-json is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with iotagent-json.
 * If not, seehttp://www.gnu.org/licenses/.
 *
 * For those usages not covered by the GNU Affero General Public License
 * please contact with::[contacto@tid.es]
 */
var config = {};

config.mqtt = {
    host: 'localhost',
    port: 1883,
    thinkingThingsPlugin: true,
    qos: 0,
    retain: false
};

config.iota = {
    logLevel: 'DEBUG',
    timestamp: true,
    contextBroker: {
        host: 'localhost',
        port: '1026'
    },
    server: {
        port: 4041
    },
    deviceRegistry: {
        type: 'mongodb'
    },
    mongodb: {
        host: 'localhost',
        port: '27017',
        db: 'iotagentjson'
    },
    types: {},
    service: 'howtoService',
    subservice: '/howto',
    providerUrl: 'http://localhost:4041',
    deviceRegistrationDuration: 'P1M',
    defaultType: 'Thing',
    defaultResource: '/iot/json'
};

config.configRetrieval = false;
config.defaultKey = '2907204D';
config.defaultTransport = 'MQTT';

module.exports = config;
```

Please try it and let me know. 

Thanks,
Fernando

**Comment by mausquirk** [comment]
Starting from scratch with an empty database did help. The iotagent now does update the Context on Orion. 
The order of setup: Device first, Service second does matter.

Thanks a lot for your support @fermenreq !
