### ISSUE TITLE
static attributes duplicated when using service as device model

### ISSUE THREAD

**Issue by agaldemas** [telefonicaid/iotagent-json#276]
Our Fiware platform is based on docker containers.
when using  iotagent-json image from fiware dockerhub it subsist a problem:
I've configured some services with some static_attributes, when I update through iotagent-json latest version, the static attributes are duplicated, then refused for update by Orion context broker.

I don't have this behavior with the fiware/iotagent-ul image, which it works perfectly since the latest fix.
and also my forked version of iotagent-json (https://github.com/agaldemas/iotagent-json) 
works fine, in the same context.

this problem doesn't seems to be a code issue, but a node_modules (package.json) version problem, don't have yet time to investigate deeper, but you can compare with my repo.

**Comment by fgalan** [comment]
Thanks for the report!

It could be great if you could include as comments to this issue the steps in order to reproduce the problem (e.g. curl commands that executed in sequence reproduce the problem).

**Comment by agaldemas** [comment]
Hello,
I won't be able to provide details now, since a lot of things have changed since...
I found other issues as of today with last version.
then I close this particular issue.

**Comment by agaldemas** [comment]
using the last version as of today I didn't noticed the same behavior
