### ISSUE TITLE
 Review and rightly process TimeInstant

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#289]
This issue is the JSON counterpart of https://github.com/telefonicaid/iotagent-ul/issues/263. In this case it is not so clear to me how timestamp is passed (query param? `"t"` field in the JSON payload? both?) but the goal will be the same:

*  Timestamp should be use as `TimeInstant` _metadata_ in the attributes included in the  measure, e.g. the attributes mapped to `t` and `r` in this case.
*  Timestamp should be use as `TimeInstant` _attribute_ in the entity corresponding to the device.

Check if the current behaviour is this one (it seems is not) and change if needed

**Comment by fgalan** [comment]
This issue has been created in the IOTA-UL repository given that the requirement has come bottom-up after analysing the UL payload. However, it could be solved in the iotagent-node-lib space (an issue should be created in that repo in that case) and be solved in general for all agents.

**Comment by manucarrace** [comment]
Some tests have been done:

Case 1:
{
  "TimeInstant": "2018-01-01T00:00:00",
  "t": "36",
  "r": "23"
}
Then, looking at the entity
TimeInstant=2018-01-01T00:00:00 (DateTime) 
t=36, TimeInstant_md=2018-01-01T00:00:00 
r=23, TimeInstant_md=2018-01-01T00:00:00


Case 2:
{
  "t": "36",
  "r": "23"
}
Then, looking at the entity
TimeInstant=<Current Time>
t=36, TimeInstant_md=<Current Time> 
r=23, TimeInstant_md=<Current Time>

I would say the behavior is correct.
