### ISSUE TITLE
Error while trying to run the IoTA in the background

### ISSUE THREAD

**Issue by saku-bambinah** [telefonicaid/iotagent-json#298]
When i tried running the ToTA in the backgroud, I got 
'Error: Cannot find module 'iotagent-node-lib''
and when i tried to look for the missing file, i could't find it in the cloned repository

**Comment by fgalan** [comment]
Did you run `npm install` before running the IOTA?

**Comment by chaima-ben-alaya** [comment]
@fgalan yes i did and I had this error

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_cacache/tmp/git-clone-01519cab
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-01519cab': Permission denied
npm ERR! 

So I used 
npm i -g npm
to overcome it

**Comment by fgalan** [comment]
Not sure if global installation is a good way of installing dependenies in this case... I haven't tested it.

I'd recommend you to solve your permissions problems first, then retry using `npm install`.

**Comment by chaima-ben-alaya** [comment]
How can I solve the permission problems?

**Comment by fgalan** [comment]
I'm afraid I cannot provide too much help... that is a aspect related with your particular operating system, related with basic user GNU/Linux administration, out of the scope of IOTAgents.

**Comment by chaima-ben-alaya** [comment]
It turned out to be a problem with npm's later version so I solved the problem using
 npm install -g npm@4

**Comment by fgalan** [comment]
Happy to know you solved the problem :)

I understand the issue can be closed, right? Thanks!
