### ISSUE TITLE
MQTT (from TTN) with Sub-Entities not work

### ISSUE THREAD

**Issue by michisnewsletter** [telefonicaid/iotagent-json#301]
We are using the [TTN](https://www.thethingsnetwork.org/) Lora Server to collect measuring points from sensors.
This server can also communicate over the MQTT protocol.

With the MQTT protocol we want to import this data into our Orion-Broker.

The Json, the input-payload for the json-MQTT-agent is

```
{
"app_id":"pace-lab",
"dev_id":"pacetemp01",
......
"payload_fields":{
"battery":4814,
"event":"interval",
"light":441,
"temperature":24.44
},
"metadata":{
"time":"2018-07-18T14:42:47.084496064Z",
"frequency":867.7,
"modulation":"LORA",
...............
...............
"location_source":"registry"
}
}
```
You can see, in our payload, the temperature-value is inside the "payload_fields" entity.
I cannot change this payload, or in other words, i cannot prevent the sub-entity 'payload-fields'

This is my payload for provisioning this device

```
"entity_name": "LivingRoomSensor",
"entity_type": "multiSensor",
"attributes": [
{ "object_id": "temperature", "name": "Temperature", "type": "celsius" }
.....
```
And that is my problem, if i try to send the upper payload (with sub-entity) (e.g. with mosquitto_pub), the iot-agent show me this error message **No context element found**

If i send this payload `{ "temperature":24.44 }`, it is working successfully.

I cannot find, how to define the sub-entity in the provisioning payload in the "attributes" ?

Thanks for you help
Michael

**Comment by fgalan** [comment]
Just to check if I'm understanding correctly, you mean that:

```
{
"app_id":"pace-lab",
"dev_id":"pacetemp01",
......
"payload_fields":{
"battery":4814,
"event":"interval",
"light":441,
"temperature":24.44
},
"metadata":{
"time":"2018-07-18T14:42:47.084496064Z",
"frequency":867.7,
"modulation":"LORA",
...............
...............
"location_source":"registry"
}
}
```

Is the MQTT payload received by the IOTA-JSON. Is my interpretation correct?

**Comment by michisnewsletter** [comment]
yes, your interpretation is correct. 
And i want to get the value of the `"temperature":24.44` and the problem is, that this "value" is in the object `payload_fields`.

**Comment by fgalan** [comment]
I think JSON objects and arrays are not allowed as measures in the southbound API. @dcalvoalonso was rencently working in this part (for the NGSIv2 adapation) and maybe he can confirm what I say or tell if I'm wrong.

Note that southbound is supposed to be a simple API to be used by devices to send simple measures. If you are sending JSON Object maybe your device is not so simple and should be interacting with the CB directly (which allows JSON Objects without problem).

As alterantive, maybe you could have a look to the transformation and bidirecttional plugins of the iotagent-node-lib library. I'm not familiar with them, but maybe they can help you to achieve what you want.

* https://github.com/telefonicaid/iotagent-node-lib#expression-translation-plugin-expressiontransformation
* https://github.com/telefonicaid/iotagent-node-lib#bidirectionality-plugin-bidirectional
* https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/expressionLanguage.md

**Comment by dcalvoalonso** [comment]
@michisnewsletter My suggestion is that you use the new [IoT Agent for LoRaWAN](https://github.com/Fiware/iot.IoTagent-LoraWAN), which supports specifically TTN messages. You have the possibility of using CayenneLpp data models or CBOR.

**Comment by michisnewsletter** [comment]
Thanks for your hint "IoT Agent for LoRaWAN", that's it.
