### ISSUE TITLE
Step-by-step: Provisioning multiple devices

### ISSUE THREAD

**Issue by norisjunior** [telefonicaid/iotagent-json#313]
In section "Provisioning multiple devices with a Configuration": 

" As you can see, the resource field is left blank (this IoT Agent doesn't make use of this field,...". 

But the "resource" variable has to be the same as in config.js. When setting the variable resource="/iot/json" the measurements were sent and read successfully. I realized this by looking at the log. I'm using Ubuntu 16.04 with Orion 0.15 (docker)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/314
