### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/iotagent-json#328]
Hello 

I have been trying to install the iotagent-json in docker and local.

In two options always have the same error:

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b: fatal: unable to connect to github.com:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b: github.com[0: 192.30.253.113]: errno=Expir? el tiempo de conexi?n
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b: github.com[1: 192.30.253.112]: errno=Expir? el tiempo de conexi?n
npm ERR! Linux 3.10.0-862.11.6.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/telefonicaid/iotagent-node-lib.git /root/.npm/_git-remotes/git-github-com-telefonicaid-iotagent-node-lib-git-master-628bad8b
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Expir? el tiempo de conexi?n
npm ERR! github.com[1: 192.30.253.112]: errno=Expir? el tiempo de conexi?n
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stack/Plataforma_seguridad/iot-agent/iotagent-json/npm-debug.log

It is impossible to install

**Comment by fgalan** [comment]
Looking to:

```
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Expir? el tiempo de conexi?n
npm ERR! github.com[1: 192.30.253.112]: errno=Expir? el tiempo de conexi?n
```

Seemt to be some kind of connection or network problem in your system. I'd say that is not related with the IOTA JSON software itself...

**Comment by amfgomez** [comment]
Hi @dcalvoalonso.

In my system has not had any connection or network problem. I have checked this problem with the following command:
cat /etc/resolv.conf ----> it works
ping 8.8.8.8 ------------> it works
sudo yum update -----> it works 

The error appears when I am compiling the docker. 
finally, I have abandoned the tool.

**Comment by dcalvoalonso** [comment]
If I understand correctly you are trying to build this [Dockerfile](https://github.com/telefonicaid/iotagent-json/blob/master/Dockerfile), right?

It would be possible for you to use the official [Docker image](https://hub.docker.com/r/fiware/iotagent-json/)?

**Comment by amfgomez** [comment]
yes, I have used the official Docker image to evaluate the tool, 
I wanted to make an own docker image with specific configurations files. 
Thank you very much

**Comment by dcalvoalonso** [comment]
A new Dockerfile has been generated using as base node:8.12.0-slim. Maybe this will solve your problems

**Comment by dcalvoalonso** [comment]
As we haven't had activity on this issue for three weeks and a new Docker has been released and tested, I suggest closing it.

What do you think @fgalan?

**Comment by fgalan** [comment]
I aggre. Closing.

@amfgomez if we are wrong, please tell us so we can reopen the issue. Thx!
