### ISSUE TITLE
Cannot read property 'findOne' AMQP

### ISSUE THREAD

**Issue by galorene** [telefonicaid/iotagent-json#329]
Hi,

Im trying "Step by Step" with AMQP binding. When i try register a new dispositive, this happens:

| comp=IoTAgent
time=2018-09-24T10:19:57.686Z | lvl=DEBUG | corr=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | trans=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | op=IoTAgentNGSI.DeviceProvisioning | srv=howtoService | subsrv=/howto | msg=Handling device provisioning request. | comp=IoTAgent
time=2018-09-24T10:19:57.687Z | lvl=DEBUG | corr=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | trans=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=howtoService | subsrv=/howto | msg=Looking for group params ["service","subservice","type"] with queryObj {"service":"howtoService","subservice":"/howto","type":"Thing"} | comp=IoTAgent
**time=2018-09-24T10:19:57.687Z | lvl=ERROR | corr=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | trans=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | op=IoTAgentNGSI.DomainControl | srv=howtoService | subsrv=/howto | msg=TypeError: Cannot read property 'findOne' of undefined | comp=IoTAgent**
time=2018-09-24T10:19:57.687Z | lvl=DEBUG | corr=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | trans=f0a80e1b-a5a9-4175-8054-bc4af8d3c3c2 | op=IoTAgentNGSI.DomainControl | srv=howtoService | subsrv=/howto | msg=response-time: 10 | comp=IoTAgent

I use the curl:
curl -X POST -H "Fiware-Service: howtoService" -H "Fiware-ServicePath: /howto" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{ 
    "devices": [ 
        { 
            "device_id": "sensor01", 
            "entity_name": "LivingRoomSensor", 
            "entity_type": "multiSensor", 
            "attributes": [ 
                  { "object_id": "t", "name": "Temperature", "type": "celsius" },
                  { "object_id": "l", "name": "Luminosity", "type": "lumens" }                  
            ]
        }
    ]
}
' 'http://localhost:4041/iot/devices'
And i get this --> **curl: (52) Empty reply from server**
This is my **docker compose** ---> https://gist.github.com/galorene/a9579a6e6afd42b1310e70743c3543da
This mi **config.js** ---> https://gist.github.com/galorene/34395ef25fc55c9dd5c439a0721cbad5
**Containers ip** --> https://gist.github.com/galorene/2b0d8dff121f1132a0303c2019082630

Thank you in advance.

**Comment by fgalan** [comment]
@galorene I see this issue has been closed. Could you elaborate a bit in how did you solve it at the end so others users in the community can benefit for the knowledgue, please? Thx!

**Comment by galorene** [comment]
@fgalan Yes. Im not sure but in my case, the problem was i have to restart all dockers if i change something on the IOTAgent docker. This was my case too on my last post in "Step by step", the next day of the post i just start the services and everything worked perfectly.
