### ISSUE TITLE
Slim could be slimmer...

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-json#343]
... with a `.dockerignore`  added to the root:

```
coverage/
node_modules/
docs/
ghpages/
test/
tools/
README.md
```

I'm not sure but can `rpm` also be added to the list?

**Comment by fgalan** [comment]
Seems to be a good idea... I understand that .dockerignore is taken into account when COPY is processed, right?

`rpm` can be also added to the list.

**Comment by fgalan** [comment]
Closed by PR #344 ?

**Comment by jason-fox** [comment]
Yes, but it should autoclose once 97d940d is merged to `master` - feel free to close it now if you wish.

**Comment by fgalan** [comment]
PR #344 merge seems to be inminent. Thus, I'm closing.
