### ISSUE TITLE
Remove Node v4

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#345]
(To be addresses in January 2019)

Node v4 will be removed by the end of 2018. In particular, this issue involves the following actions:

* Node v4 should be removed from .travis.yml
* engine version should be modified to be >=6 in packages.json
* logops library should be updated to 2.1.0 in packages.json

**Comment by Jagatjot** [comment]
@dcalvoalonso After I remove the Node.js v4 from .travis.yml and upgrade logops to 2.1.0 test fails with the below mentioned error-
 1) AMQP Transport binding: commands
       When a command arrive to the Agent for a device with the AMQP protocol
         should publish the command information in the AMQP topic:
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/telefonicaid/iotagent-json/test/unit/commandsAmqp-test.js)
      at _combinedTickCallback (internal/process/next_tick.js:77:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by Jagatjot** [comment]
@fgalan I have upgraded logops to 2.1.0 in the PR and tests passes successfully. Thanks!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/349
