### ISSUE TITLE
Remove Node v6

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#346]
(To be addresses in May 2019)

Node v6 ends support in April 2019 (see https://github.com/nodejs/Release) and should be removed by that date. In particular, this issue involves the following actions:

* Node v6 should be removed from .travis.yml
* engine version should be modified to be >=8 in packages.json

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/issues/346

**Comment by Chandradeep-NEC** [comment]
HI @fgalan 
If the PR #400  has been merged then please close this issue.

**Comment by fgalan** [comment]
> HI @fgalan
> If the PR #400 has been merged then please close this issue.

It seem I missed doing so when the PR was merged time ago... Thanks for noticing!

**Comment by jason-fox** [comment]
> > HI @fgalan
> > If the PR #400 has been merged then please close this issue.
> 
> It seem I missed doing so when the PR was merged time ago... Thanks for noticing!

This issue still needs closing
