### ISSUE TITLE
Wrong mirror webhook config

### ISSUE THREAD

**Issue by caa06d9c** [telefonicaid/iotagent-json#356]
Please, change the mirror webhook config as described [here](https://fiware-requirements.readthedocs.io/en/latest/repo_webhook/index.html)

**Comment by fgalan** [comment]
Updated. Now it looks:

![imagen](https://user-images.githubusercontent.com/1534240/49799808-24b24100-fd46-11e8-8df8-2ee1bcd5c9e4.png)

Please check it and close the issue if it is working fine. Thx!

**Comment by caa06d9c** [comment]
Checked. Thanks!
