### ISSUE TITLE
[MUST] Every GE must have training materials

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-json#368]
At the moment this enabler has no Tutorial and no link to the Academy and does not fulfil the minimum **Training** section requirements. 

The suggestion is to create a simple *Attaching other IoT Agents tutorial*  to provide a series of simple hello world connections for each agent in turn - this needs to include 

* One docker compose file for base config
* A set of REST API calls to provision the service
* An indication on how to make  minimal measure arrive (e.g. publishing an MQTT topic or equivalent)
* Proof that the data arrives in Orion.

- Presence of training  is a MUST requirement

**Comment by fgalan** [comment]
What about the materials in the Academy at https://fiware-academy.readthedocs.io/en/latest/iot-agents/idas/index.html? It is a matter of just linking the from the main README.md?

**Comment by jason-fox** [comment]
The Academy is where the links will end up, and yes the readme will need a link in the link box, but unlike Lightweight M2M , Node Lib and Ultralight, there is nothing within the training materials in the Academy specific to the **JSON** IoT agent 

For example the general  IoT Agent stuff usually relates to the IoT library or Ultralight (such as the video) , and there is something specific on LWM2M. It could be that the basic step-by-step connection stuff exists somewhere, but its not in the Academy ... yet.

The LoRaWAN Agent has a basic _how-to-connect-and-see-this-working_ document which will be added as example code to fulfill this see - https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/38

As it is, if I don't know how the JSON IoT Agent works I can't test each link in the change to see if my connection is right, and not all the information regarding the other agents is relevant to JSON.

**Comment by fgalan** [comment]
What about using https://thinking-cities.readthedocs.io/en/latest/device_api/index.html?

It covers both UL and JSON.

**Comment by jason-fox** [comment]
Hmmm. Training materials are much easier to follow if they are focused. Looking at the [issues](https://github.com/telefonicaid/iotagent-json/issues) backlog, I noticed you have [this](https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md) - which is  a JSON specific  _how-to-connect-and-see-this-working_ document. It just needs links added into the academy in the same manner.

The point here is that it shouldn't be up to the new user to try to find them, they should be available and prominently linked in all the the right places, you shouldn't have to search for them.

So now that we've found it, could you assign this Issues to me and leave it **open** for now (so it doesn't get lost) and I'll add it to the academy in a standard format.

**Comment by fgalan** [comment]
Great! I didn't remember that piece of doc. Sorry...

You have been assigned. Thanks!
