### ISSUE TITLE
[SHOULD] Repo description, topics and URL link

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-json#371]
Please click the edit button at the head of the repo and amend the description link and topics as shown (or similar):

### Link

> https://fiware-iotagent-json.rtfd.io/

### Topics

`fiware`, `iot`, `iot-agent`

- SHOULD requirement from the TSC.

**Comment by fgalan** [comment]
Done!

Please have a look and close the issue if you find it solved.
