### ISSUE TITLE
include agent protocol in topic (MQTT)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#374]
twin issue https://github.com/telefonicaid/iotagent-ul/issues/287

Currently topics used by iotagent-json and iotagent-ul are the same.
/<apikey>/<device_id>/attrs
There is no way to know if a topic (MQTT) is for UL or JSON agent.

Topic is fixed in agent source code:

    https://github.com/telefonicaid/iotagent-json/blob/master/lib/bindings/MQTTBinding.js#L45
    https://github.com/telefonicaid/iotagent-ul/blob/master/lib/bindings/MQTTBinding.js#L46

Topic is knowed by ACL files:

    https://github.com/telefonicaid/iotagent-node-lib/blob/master/docker/Mosquitto/aclfile#L3
    https://github.com/telefonicaid/rabbit-topic-acl/blob/master/docker/aclfile#L2

Possible solution: extending topics
```
/<protocol>/<apikey>/<device_id>/attrs
```
but is not backward compatible

**Comment by fgalan** [comment]
Implemented in PR #450 

Can this issue be closed? Or is there anything pending?
