### ISSUE TITLE
[MUST] Show versioned documentation

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-json#378]
On the IoT JSON Agent ReadtheDocs project, no versioned documentation is displayed

- Goto https://readthedocs.org/projects/fiware-iotagent-json/versions/
- Ensure that **active** checkmark is ticked against relevant release tags

**Comment by fgalan** [comment]
I cannot help, as I don't admin this RTD project. It seems that @jmcanterafonseca does, so maybe he can take care of this issue.

**Comment by jmcanterafonseca** [comment]
I've enabled the latest release. I think it can suffice. now @fgalan is also project maintainer at rtd
