### ISSUE TITLE
[MUST] Roadmap is missing

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-json#379]
A roadmap for the project for the short (3 months) , medium (one year) and long term  should be added to the repository and publicly available.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/384

**Comment by fgalan** [comment]
@jason-fox I understand that PR #759 solves this issue but if I'm wrong please reopen an explain what is missing.
