### ISSUE TITLE
Device discovery in iotagent-json

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/iotagent-json#383]
Is device discovery possible in iotagent-json?
My expectation from device discovery is that whenever a new device gets registered in iotagent-json, I receive a notification with device data.

**Comment by fgalan** [comment]
This seems to be more a question/doub than an issue on the software. Thus, could you post it using StackOverflow https://stackoverflow.com, please? Use the "fiware" label please.

Once done, please add the link to the question in this issue. Then close the issue.

Thanks!

**Comment by pooja1pathak** [comment]
As suggested by you, I have posted this question on [StackOverflow](https://stackoverflow.com/questions/54780854/device-discovery-in-fiware-iotagent-json)
