### ISSUE TITLE
Add : Multimeasure support

### ISSUE THREAD

**Issue by Jagatjot** [telefonicaid/iotagent-json#391]
Does iotagent-json support this kind of request?

```
curl -X POST \
  'http://<IP>:7896/iot/json?i=hhr_device&k=123' \
  -H 'content-type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
-d '{
"deviceName": "Sensor1",
"devicetype": "Sensor",
"devicedata": "10",
"deviceMacId": "84:24:8D:EE:2F:D2"},
{
"deviceName": "Sensor1",
"devicetype": "Sensor",
"devicedata": "11",
"deviceMacId": "84:24:8D:EE:2F:D2"},
{
"deviceName": "Sensor1",
"devicetype": "Sensor",
"devicedata": "12",
"deviceMacId": "84:24:8D:EE:2F:D2"},



If yes, what should be the request format or what needs to be enabled for that?

**Comment by fgalan** [comment]
Have you tried it in an existing IOTA-JSON? Which response did you get?

**Comment by Jagatjot** [comment]
@fgalan @jason-fox Is the above request supported in iotagent-json?

**Comment by fgalan** [comment]
What is on position 202?

**Comment by Jagatjot** [comment]
@fgalan Actually I want to send same attribute multiple times in a single request. iotagent-ul supports this, we can send the request with # to send two values of t in one request (t|4#t|10). I need to do the same in iotagentjson but it isn't supporting ?

**Comment by Jagatjot** [comment]
The syntax error is of "," which is at the end of this line "deviceMacId": "84:24:8D:EE:2F:D2"},

**Comment by fgalan** [comment]
In that case I'd suggest to adjust the tittle of the issue from "Curl request to send device measure" (too broad) to "Multimeasure support" (precise enougth).

In fact, maybe is there any existing issue about "Multimeasure support"? Or maybe it's already supported in the agent? Have you reviewed the documentation?

**Comment by Jagatjot** [comment]
"Multimeasure support" is already supported for non-overlapping set of attributes. But it doesn't work in case of overlapping attributes as given in https://github.com/telefonicaid/iotagent-json/issues/391#issue-420457269

**Comment by fgalan** [comment]
Do you have the link to the documentation where the multimeasure support is described in the IOTA-JSON documentation? I'd lilke to have a look...

**Comment by Jagatjot** [comment]
https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md in Provisioning multiple devices with a Configuration two different attributes(humidity and happiness) are send in the documentation. I want to send value humidity more than one time in a request.

**Comment by chandradeep03** [comment]
@Jagatjot the request format should be as below:

curl -X POST \
  'http://<IP>:7896/iot/json?i=hhr_device&k=123' \
  -H 'content-type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '[{
"deviceName": "FIXED READER",
"locationType": "O",
"locationTypeId": "10",
"locationName": "Noida",
"locationId": "0003",
"devicetype": "FR",
"deviceMacId": "84:24:8D:EE:2F:D2"},
{
"deviceName": "FIXED READER",
"locationType": "O",
"locationTypeId": "10",
"locationName": "Delhi",
"locationId": "0002",
"devicetype": "FR",
"deviceMacId": "84:24:8D:EE:2F:D2"},
{
"deviceName": "FIXED READER",
"locationType": "O",
"locationTypeId": "10",
"locationName": "Gurgaon",
"locationId": "0001",
"devicetype": "FR",
"deviceMacId": "84:24:8D:EE:2F:D2"}]'

I've added square bracket i.e. "[]" in data to make it in array format.

**Comment by fgalan** [comment]
Thanks @chandradeep03 for the support.

@Jagatjot could you have a look and close if that solves the problems, please? Thanks!

**Comment by Jagatjot** [comment]
@chandradeep03 Thank you for your support. This PR solves our problem.

**Comment by Jagatjot** [comment]
@fgalan Can we merge this PR in master ?

**Comment by fgalan** [comment]
@Jagatjot to which PR do you refer? I'm looking into https://github.com/telefonicaid/iotagent-json/pulls and I don't see anything related...

**Comment by Jagatjot** [comment]
> @Jagatjot to which PR do you refer? I'm looking into https://github.com/telefonicaid/iotagent-json/pulls and I don't see anything related...

The PR referenced in this issue

**Comment by fgalan** [comment]
@Jagatjot do you mean https://github.com/chandradeep03/iotagent-json/pull/1?

Note that PR was not done on this repository (https://github.com/telefonicaid/iotagent-json) but in a different fork (https://github.com/chandradeep03/iotagent-json) so somebody ( @chandradeep03 ? you?) should create a new PR on this repository so we can have a look, review and eventually merge.

Thanks!

**Comment by Jagatjot** [comment]
> @Jagatjot do you mean [chandradeep03#1](https://github.com/chandradeep03/iotagent-json/pull/1)?
> 
> Note that PR was not done on this repository (https://github.com/telefonicaid/iotagent-json) but in a different fork (https://github.com/chandradeep03/iotagent-json) so somebody ( @chandradeep03 ? you?) should create a new PR on this repository so we can have a look, review and eventually merge.
> 
> Thanks!

Yes, the PR raised by @chandradeep03

**Comment by fgalan** [comment]
Thanks for the clarification. So, should I understand that you or @chandradeep03 are going to create a PR on this repository to merge that code in the telefonicaid/iotagent-json, please? Thanks!

**Comment by chandradeep03** [comment]
@fgalan I have raised the PR for issue #391 please check and review the same

**Comment by fgalan** [comment]
At this moment:

* PR https://github.com/telefonicaid/iotagent-json/pull/396 implements multimeasures for HTTP
* PR https://github.com/telefonicaid/iotagent-json/pull/459 provides documentation for such implementation

What is pending after this couple of PR: implement multimeasures for MQTT and AMPQ transports (and modifiy the IMPORTANT NOTE in documentation accordingly)

**Comment by fgalan** [comment]
Follow up issue for the pending part: https://github.com/telefonicaid/iotagent-json/issues/462.

This one is going to be closed.

**Comment by Chandradeep-NEC** [comment]
@fgalan 
Thanks for closing the issue :)
The issues #391 and #462 should be labeled as Feature.

**Comment by fgalan** [comment]
Ok. Done.
