### ISSUE TITLE
Returning empty value from iotagent-json to Orion in case if no value is passed from Device to iotagent-json

### ISSUE THREAD

**Issue by chandradeep03** [telefonicaid/iotagent-json#395]
**Current behaviour**
As per the current behaviour of Orion, if some attribute has not passed from device to iotagent-json then in this case, Orion will assign the previous value to those attribute. 

**Problem:**
But if it is required as Orion should consider empty value i.e. "" for such attributes then currently it is not possible.

Please check the below is the example for more understanding:
**Device Provisioning:**
curl -X POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
        "devices": [{
                "device_id": "device03",
                "entity_name": "sensor01",
                "entity_type": "sensortest",
                "attributes": [{
                        "object_id": "wagnonNo",
                        "name": "wagnonNo",
                        "type": "int"
                },{
                        "object_id": "ContainerNo",
                        "name": "ContainerNo",
                        "type": "int"
                },{
                        "object_id":"macAddress",
                        "name": "macAddress",
                        "type": "string"
                }]}]
}'

**First time data passed from device to IOT agent::**
curl -X POST \
  'http://localhost:7896/iot/json?i=device03&k=testkey01' \
  -H 'content-type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "wagnonNo": "900",
  "containerNo": "5000",
  "macAddress": "84:24:8D:EE:2F:D1"
  }'

**2nd time data pass from device to iotagent-json**
curl -X POST \
  'http://10.0.2.15:7896/iot/json?i=sensor01&k=testkey01' \
  -H 'content-type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "wagnonNo": "901",
  "macAddress": "22:54:8A:EC:2B:B6"
  }'

**Output at Orion after passing 2nd data as per current feature:**
{
    "id": "sensor01",
    "type": "sensortest",
    "TimeInstant": {
        "type": "ISO8601",
        "value": "2019-04-05T08:44:43.00Z",
        "metadata": {}
    },
    "wagnonNo": {
        "type": "string",
        "value": "901",
        "metadata": {
            "TimeInstant": {
                "type": "ISO8601",
                "value": "2019-04-05T08:44:43.914Z"
            } }},
    "containerNo": {
        "type": "string",
        "value": "5000",
        "metadata": {
            "TimeInstant": {
                "type": "ISO8601",
                "value": "2019-04-05T08:44:43.914Z"
            }}},
    "macAddress": {
        "type": "string",
        "value": "22:54:8A:EC:2B:B6",
        "metadata": {
            "TimeInstant": {
                "type": "ISO8601",
                "value": "2019-04-05T08:44:43.914Z"
            }} }}

**Expected output**
{
    "id": "sensor01",
    "type": "sensortest",
    "TimeInstant": {
        "type": "ISO8601",
        "value": "2019-04-05T08:44:43.00Z",
        "metadata": {}
    },
    "wagnonNo": {
        "type": "string",
        "value": "901",
        "metadata": {
            "TimeInstant": {
                "type": "ISO8601",
                "value": "2019-04-05T08:44:43.914Z"
            }} },
    "containerNo": {
        "type": "string",
        **"value": "",**
        "metadata": {
            "TimeInstant": {
                "type": "ISO8601",
                "value": "2019-04-05T08:44:43.914Z"
            }} },
    "macAddress": {
        "type": "string",
        "value": "22:54:8A:EC:2B:B6",
        "metadata": {
            "TimeInstant": {
                "type": "ISO8601",
                "value": "2019-04-05T08:44:43.914Z"
            } }}}

**Comment by fgalan** [comment]
This issue seems to be an exact clone of https://github.com/telefonicaid/iotagent-node-lib/issues/771. Or is there any difference?

If I'm correct I understand it should be closed. Please avoid double-posting the same issue in two places. Let's try to avoid duplications. Thanks!

**Comment by chandradeep03** [comment]
Yes. this issue is clone of #771.
I'll close it from here i.e. Issue #395
