### ISSUE TITLE
AMPQ is not configured, but agent tries to connect

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-json#409]
```
time=2019-06-22T14:57:13.964Z | lvl=ERROR | corr=14861347-d7d1-411f-88a5-5784a9f21adf | trans=14861347-d7d1-411f-88a5-5784a9f21adf | op=IOTAJSON.AMQP.Binding | srv=n/a | subsrv=n/a | msg=connect ECONNREFUSED 127.0.0.1:5672 | comp=IoTAgent
```
this is due to the fact that if ampq is not configured, a connection to localhost is automatically created. see:
https://github.com/telefonicaid/iotagent-json/blob/master/lib/bindings/AMQPBinding.js#L114

**Comment by fgalan** [comment]
I understand the solution to this is not connect to AMQP if the element has not been defined in the configuration (MQTT works in a similar way?)

What's the situation in IOTA-UL? Does it have the same problem? In that case, it would be great to solve at the same time (although in different PRs, of course, one per repo) 

Thanks for the report!

**Comment by Madhu-NEC** [comment]
Hi @fgalan , @chicco785 
In case of MQTT i.e. var **config.mqtt** is missing in config.js, IOTAgent throws below exception.

`time=2019-10-04T04:34:02.079Z | lvl=ERROR | corr=e2b8d582-8fa3-4fed-94b8-404c3bc
cb634 | trans=e2b8d582-8fa3-4fed-94b8-404c3bccb634 | op=IoTAgentNGSI.DomainContr
ol | srv=n/a | subsrv=n/a | msg={ TypeError: Cannot read property 'thinkingThing
sPlugin' of undefined
    at D:\IOT_Agent\iotagent-json-master\lib\iotagent-json.js:140:40
    at D:\IOT_Agent\iotagent-json-master\node_modules\iotagent-node-lib\node_mod
ules\async\dist\async.js:3888:9
    at D:\IOT_Agent\iotagent-json-master\node_modules\iotagent-node-lib\node_mod
ules\async\dist\async.js:473:16
    at replenish (D:\IOT_Agent\iotagent-json-master\node_modules\iotagent-node-l
ib\node_modules\async\dist\async.js:1006:25)
    at iterateeCallback (D:\IOT_Agent\iotagent-json-master\node_modules\iotagent
-node-lib\node_modules\async\dist\async.js:995:17)`

As per my understanding, if AMQP or MQTT is not configured i.e. missing **var config.mqtt and var config.amqp** configuration in config.js, IOT Agent should not connect to these services and return an **error log** statement like "**AMQP is not configured**".
Please confirm my understanding.

**Comment by fgalan** [comment]
Makes sense.

If you have located the part of the code dealing with this, maybe you could contribute with a pull request fixing it, please? Thanks!

**Comment by fgalan** [comment]
(In fact, one PR to this repository and another to https://github.com/telefonicaid/iotagent-ul. I understand both agents behave the same regarding this)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/433

**Comment by Chandradeep-NEC** [comment]
HI @fgalan 
As @Madhu-NEC  has worked on this issue. Please assigned it to her.
Thanks :)

**Comment by fgalan** [comment]
Done!
