### ISSUE TITLE
In mqtt set default keepalive parameter to default mqtt software value 60 seconds

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/iotagent-json#413]
In mqtt set default keepalive parameter to default mqtt software value 60 seconds

See: https://www.npmjs.com/package/mqtt or https://github.com/mqttjs/MQTT.js#connect

**Comment by AlvaroVega** [comment]
Now this is a parameter, configurable in config.js or env var, so you can set the value that you want. Default is 0.

**Comment by fgalan** [comment]
So probably this issue should be closed. @cesarjorgemartinez what do you think?

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/525
