### ISSUE TITLE
In mqtt set clean parameter to false

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/iotagent-json#414]
In mqtt set clean parameter to false

clean: true, set to false to receive QoS 1 and 2 messages while offline

See: https://www.npmjs.com/package/mqtt or https://github.com/mqttjs/MQTT.js#connect

**Comment by manucarrace** [comment]
As far as i know the flag disable-clean-session can be set by a client in the subscription. This will allow devices to retrieve commands when they subscribe to the broker, no matter when the command is sent. The id is also needed. The request would be like this:

mosquitto_sub --disable-clean-session --id 1 -q 2 -d -h <ip> -p <port> -u <user> -P <password> -t <command_topic>

So, nothing to do with the agent from my point of view.

**Comment by fgalan** [comment]
@cesarjorgemartinez , based in @manucarrace feeedback, can this issue be closed?

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/562
