### ISSUE TITLE
Selectively ignore some measures

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#416]
Support selective ignore of measures so the IOTA doesn't progress for instance the measure on `m` when it receives `{"n": 044.7, "m": 30}`.

**Comment by fgalan** [comment]
Twin issue in IOTA-UL: https://github.com/telefonicaid/iotagent-ul/issues/372

**Comment by Chandradeep-NEC** [comment]
Hi @fgalan,
Please confirm if there is anyone working on this issue?

**Comment by fgalan** [comment]
> Hi @fgalan,
> Please confirm if there is anyone working on this issue?

No, as far as I know. Thanks!

**Comment by Madhu-NEC** [comment]
Hi @fgalan ,

As per my understanding, the feature development is about when one or more attributes set as ignored then these attributes should not be updated at Context Broker.

Following are the possible cases by which we can implement above feature:
**Case 1**: Set attributes to be ignored at the time of device registration. The sample payloads for device registration can be:
**Approach 1**: An **ignoredAttrs** key is added to ignore the attributes.
```
"devices": [{
                "device_id": "hhr_device",
                "entity_name": "data_raw",
                "entity_type": "data",
                "protocol":"IoTA-JSON",
                "attributes": [{
                        "object_id": "A",
                        "name": "A",
                        "type": "string"
                },{
                        "object_id": "B",
                        "name": "B",
                        "type": "string"
                },{
                        "object_id": "C",
                        "name": "C",
                        "type": "int"
                }],
		"ignoredAttrs": ["A","C"]
		}]
```
OR
**Approach 2**: A flag **ignored** is added to each attribute to ignore the attribute.
```
"devices": [{
                "device_id": "hhr_device",
                "entity_name": "data_raw",
                "entity_type": "data",
                "protocol":"IoTA-JSON",
                "attributes": [{
                        "object_id": "A",
                        "name": "A",
                        "type": "string",
			"ignored": "true"
                },{
                        "object_id": "B",
                        "name": "B",
                        "type": "string",
                        "ignored": "false"
                },{
                        "object_id": "C",
                        "name": "C",
                        "type": "int",
			"ignored": "true"
                }]
		}]
```
			
**Case 2**: Set attributes to be ignored while sending measure to the IOTA. The sample payload for sending measure is:

```
  -d '{
        "A": "a",
	"B": "b",
	"C": "c",
	"ignoredAttrs": ["A","C"]
}'
```

As per my understanding, Case 1-Approach 1 will be the good approach to solve this.
Please confirm my understanding.

**Comment by fgalan** [comment]
The current behavior is that any measure sent by the device progresses toward Orion, no matter if it is part of "attributes" field or not ("attributes" field is only used to apply a mapping, a transformation expression, etc.).

I'd suggest to implement this using a flag. For instance, "explicitAttrs": true|false. If true, only the attributes declared in "attributes" will be progressed, the rest will be ignored.

This explicitAttrs flag could be defined at three levels:

* Agent configuration (i.e. config.js and corresponding env var), default setting if explicitAttrs is not defined at cgroup or device provisioning time. Default (i.e. if "explicitAttrs" is omitted in this configuation) should be false (in order to keep backward compatibility).
* "explicitAttrs" field in the JSON payload in POST /iot/services provision operation, overriding the setting at agent level.
* "explicitAttrs" field in the JSON payload in POST /iot/devices provision operation, overriding the setting at service level.

Does it make sense? Please, don't hesitate to ask if you have doubts about this proposal.

**Comment by fgalan** [comment]
Note that the provisioning API is part of the functionality provided by iotatent-node-lib so maybe this functionality needs modification to that library (and not to the agents code) to be implemented.

**Comment by Madhu-NEC** [comment]
Hi @fgalan 
> The current behavior is that any measure sent by the device progresses toward Orion, no matter if it is part of "attributes" field or not ("attributes" field is only used to apply a mapping, a transformation expression, etc.).

As per my understanding, the current behavior is different for 'v1'.
For instance:
Device is provisioned using below request. Only measure `c` is part of "attributes" field:
![device_registration](https://user-images.githubusercontent.com/47887616/69697360-3a13ad00-1108-11ea-8c84-f25579c72a1c.png)

Below are the two cases for sending measure if it is not part of "attributes".
**Case 1**: When `ngsiVersion` is not set in `config.js`. The measure is sent using v1 and it gives 404 DEVICE_NOT_FOUND error but attribute `c` gets updated at Orion as well. Below is the screenshot
![sending_measure_v1_unregistered_attributes](https://user-images.githubusercontent.com/47887616/69697377-413abb00-1108-11ea-94fa-c7f39d740f4e.png)

**Case 2**: When `ngsiVersion: 'v2'` is set in `config.js`. The measure is sent using v2 and it gives 200 OK and both measures are progressed toward Orion. Below is the screenshot
![sending_measure_v2_unregistered_attributes](https://user-images.githubusercontent.com/47887616/69697388-46980580-1108-11ea-87f0-9dbc409221b9.png)

So, as per above explanation, the feature will be implemented for v2 only.
Please confirm.

**Comment by Madhu-NEC** [comment]
Hi @fgalan ,
Could you please share your opinion?

**Comment by fgalan** [comment]
NGSIv1 is a deprecated API so I'd suggest to focus in the NGSIv2 case.

As far as I understand by your test, in NGSIv2 the behaviour

> The current behavior is that any measure sent by the device progresses toward Orion, no matter if it is part of "attributes" field or not ("attributes" field is only used to apply a mapping, a transformation expression, etc.).

happens, so my proposal of soultion

> I'd suggest to implement this using a flag. For instance, "explicitAttrs": true|false. If true, only the attributes declared in "attributes" will be progressed, the rest will be ignored.
> 
> This explicitAttrs flag could be defined at three levels:
> 
> * Agent configuration (i.e. config.js and corresponding env var), default setting if explicitAttrs is not defined at cgroup or device provisioning time. Default (i.e. if "explicitAttrs" is omitted in this configuation) should be false (in order to keep backward compatibility).
> 
> * "explicitAttrs" field in the JSON payload in POST /iot/services provision operation, overriding the setting at agent level.
> 
> * "explicitAttrs" field in the JSON payload in POST /iot/devices provision operation, overriding the setting at service level.

would be applicable.

Does it makes sense to you? Do you agree in implementing that solution?

Please tell me what you think. Thanks!

**Comment by fgalan** [comment]
By the way, I think this issue has relation with this other: https://github.com/telefonicaid/iotagent-node-lib/issues/654. In particular, this issue seems to correspond to "case 2" of https://github.com/telefonicaid/iotagent-node-lib/issues/654.

**Comment by Chandradeep-NEC** [comment]
@fgalan 
Please assign this issue to @Madhu-NEC 

Thanks :)

**Comment by fgalan** [comment]
Done!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/458 (and https://github.com/telefonicaid/iotagent-node-lib/pull/873)
