### ISSUE TITLE
Error "Cannot read property 'find' of undefined"

### ISSUE THREAD

**Issue by leonardorodd** [telefonicaid/iotagent-json#425]
Hi,
I try to create (and get) device from iot agentJSON/HTTP (Docker Container) but I had error message in LOG :

op=IoTAgentNGSI.GenericMiddlewares | srv=howtoservice | subsrv=/howto | msg=Error [TypeError] handling request: Cannot read property 'find' of undefined | comp=IoTAgent

GET FROM /iot/services or POST return HTTP ERROR 500
{
  "name": "TypeError",
  "message": "Cannot read property 'find' of undefined"
}

I use docker image fiware/iotagent-json:latest

Thanks,

**Comment by fgalan** [comment]
Could you detail the sequence of steps you have followed to reproduce the steps (from the moment in which you start the container to the point in which you get the above response), please?

That information would be very useful to debug the case. Thanks!

**Comment by leonardorodd** [comment]
The Orion Context Broker and the MongoDB are running. I followed this guide 
https://fiware-tutorials.readthedocs.io/en/latest/getting-started/index.html

Using this section:

OPTION 2) USING DOCKER COMPOSE
All services can be initialised from the command-line using the docker-compose command. Please clone the repository and create the necessary images by running the commands as shown:

git clone git@github.com:FIWARE/tutorials.Getting-Started.git
cd tutorials.Getting-Started

docker-compose -p fiware up -d

For the IoT Agent:
I followed this guide: https://fiware-iotagent-json.readthedocs.io/en/latest/installationguide/index.html

Using the docker section
docker run -it --init -v <path-to-myconfiguration-file>:/opt/iotajson/new_config.js fiware/iotagent-json  -- new_config.js

And I see this in the IoT Agent console:
{
    "logLevel": "DEBUG",
    "timestamp": true,
    "contextBroker": {
        "host": "172.18.1.3",
        "port": "1026",
        "url": "http://172.18.1.3:1026"
    },
    "server": {
        "port": 4041
    },
    "deviceRegistry": {
        "type": "mongodb"
    },
    "mongodb": {
        "host": "172.18.1.2",
        "port": "27017",
        "db": "iotagentjson"
    },
    "types": {},
    "service": "howtoservice",
    "subservice": "/howto",
    "providerUrl": "http://localhost:4041",
    "deviceRegistrationDuration": "P1M",
    "defaultType": "Thing",
    "defaultResource": "/iot/json",
    "iotaVersion": "1.11.0-next"
}

**Comment by fgalan** [comment]
This issue has been closed. Should I understand you finally solved the problem? Could you include some information about what the solution was, please? That information can be useful for other people in the community using the component.

Thanks!
