### ISSUE TITLE
Log always writes the same correlator and transaction id

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-json#426]
Tween issue as https://github.com/telefonicaid/iotagent-ul/issues/326

**Comment by DeepshikhaNEC** [comment]
@manucarrace In the current scenario the corr id and trans id is associated with the domain.js which is created once when the application is started and active for the complete running application.
That’s why it is giving the same value every time.

As per my understanding to change the corr id and trans id, we need to clean the domain and create it again or re-write the both of the id’s associated to the domain. 
Please let me know your opinion. What are the scenarios on which the corr id and trans id need to change?

**Comment by fgalan** [comment]
> What are the scenarios on which the corr id and trans id need to change?

As a general rule (applying to all FIWARE components logging this way), corrid is defined as the ID for an e2e flow, while transid is defined as the ID for a given transaction within the e2e flow. In the case of IOTAs I'd say that all e2e flows correspond to a single transaction, so both can be treated the same way (how it works right now? corrid is equal to transid in the same log message? that is a valid solution in the case of IOTAs, from my point of view).

corrid should change in each new transaction (i.e. each new measure received at southbound interface and each new request of the provision API in the northbound interface) and keep the same in all the log messages related with that transaction.

I hope this information clarifies the issue.

**Comment by fgalan** [comment]
Moreover, I tried to solve this in the past, with PR https://github.com/telefonicaid/iotagent-ul/pull/327. The PR is old and I wasn't able to complete the work, but maybe is useful to you to continue the work from that point.

**Comment by DeepshikhaNEC** [comment]
> Moreover, I tried to solve this in the past, with PR [telefonicaid/iotagent-ul#327](https://github.com/telefonicaid/iotagent-ul/pull/327). The PR is old and I wasn't able to complete the work, but maybe is useful to you to continue the work from that point.

@fgalan Hi, As per my understandanding it is already fixed for all type of http request and i need to fix it only for mqtt and amqp request. Please confirm me is it correct?

**Comment by fgalan** [comment]
> @fgalan Hi, As per my understandanding it is already fixed for all type of http request and i need to fix it only for mqtt and amqp request. Please confirm me is it correct?

Yes. I think you understanding is correct. Thanks!

**Comment by DeepshikhaNEC** [comment]
@fgalan Hi, I have fixed this issue #426. For this PR has been raised in iotagent-json as well as iotagent-node-lib. 

Request you to please confirm the same and if the PR is ok then please merge it in master branch.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/478 (and https://github.com/telefonicaid/iotagent-node-lib/pull/864)
