### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by leonardorodd** [telefonicaid/iotagent-json#428]
when sending a command to a device through Orion, I have this error in IoT Agent console

time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentJSON.Commands | srv=n/a | subsrv=n/a | msg=Sending command execution to device [1234] with apikey [motorservo] and payload [{"name":"mover","type":"command","value":""}]  | comp=IoTAgent
time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Creating execution for function [executeCommand] and protocol [HTTP] | comp=IoTAgent
time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Binding found for function [executeCommand] and protocol [HTTP] | comp=IoTAgent
time=2019-09-10T12:35:11.663Z | lvl=ERROR | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.DomainControl | srv=n/a | subsrv=n/a | msg={ TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/opt/iotajson/lib/bindings/HTTPBinding.js:126:67)
    at self.callback (/opt/iotajson/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/opt/iotajson/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: domainErrorHandler] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [ [Object] ],
     start: 1568118873386,
     trans: '10bc0144-84ef-4d47-b960-096937292131',
     corr: '10bc0144-84ef-4d47-b960-096937292131',
     op: 'IoTAgentNGSI.MongoDBGroupRegister' },
  domainThrown: true } | comp=IoTAgent

**Comment by leonardorodd** [comment]
1234 is my apikey, don't the device name.

**Comment by leonardorodd** [comment]
response from the IoT Agent sending a request for http://172.18.1.4:4041/iot/devices
{
  "count": 1,
  "devices": [
    {
      "device_id": "motorservo",
      "service": "howtoservice",
      "service_path": "/howto",
      "entity_name": "urn:ngsi-ld:Thing:motorservo",
      "entity_type": "Thing",
      "endpoint": "http://localhost:2000/moverservo",
      "transport": "HTTP",
      "attributes": [],
      "lazy": [],
      "commands": [
        {
          "object_id": "mover",
          "name": "mover",
          "type": "command"
        }
      ],
      "static_attributes": []
    }
  ]
}

**Comment by leonardorodd** [comment]
> when sending a command to a device through Orion, I have this error in IoT Agent console
> 
> time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentJSON.Commands | srv=n/a | subsrv=n/a | msg=Sending command execution to device [1234] with apikey [motorservo] and payload [{"name":"mover","type":"command","value":""}] | comp=IoTAgent
> time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Creating execution for function [executeCommand] and protocol [HTTP] | comp=IoTAgent
> time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Binding found for function [executeCommand] and protocol [HTTP] | comp=IoTAgent
> time=2019-09-10T12:35:11.663Z | lvl=ERROR | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.DomainControl | srv=n/a | subsrv=n/a | msg={ TypeError: Cannot read property 'statusCode' of undefined
> at Request._callback (/opt/iotajson/lib/bindings/HTTPBinding.js:126:67)
> at self.callback (/opt/iotajson/node_modules/request/request.js:185:22)
> at emitOne (events.js:116:13)
> at Request.emit (events.js:211:7)
> at Request.onRequestError (/opt/iotajson/node_modules/request/request.js:881:8)
> at emitOne (events.js:116:13)
> at ClientRequest.emit (events.js:211:7)
> at Socket.socketErrorListener (_http_client.js:401:9)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at emitErrorNT (internal/streams/destroy.js:66:8)
> at _combinedTickCallback (internal/process/next_tick.js:139:11)
> at process._tickDomainCallback (internal/process/next_tick.js:219:9)
> domain:
> Domain {
> domain: null,
> _events: { error: [Function: domainErrorHandler] },
> _eventsCount: 1,
> _maxListeners: undefined,
> members: [ [Object] ],
> start: 1568118873386,
> trans: '10bc0144-84ef-4d47-b960-096937292131',
> corr: '10bc0144-84ef-4d47-b960-096937292131',
> op: 'IoTAgentNGSI.MongoDBGroupRegister' },
> domainThrown: true } | comp=IoTAgent



> when sending a command to a device through Orion, I have this error in IoT Agent console
> 
> time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentJSON.Commands | srv=n/a | subsrv=n/a | msg=Sending command execution to device [1234] with apikey [motorservo] and payload [{"name":"mover","type":"command","value":""}] | comp=IoTAgent
> time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Creating execution for function [executeCommand] and protocol [HTTP] | comp=IoTAgent
> time=2019-09-10T12:35:11.650Z | lvl=DEBUG | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Binding found for function [executeCommand] and protocol [HTTP] | comp=IoTAgent
> time=2019-09-10T12:35:11.663Z | lvl=ERROR | corr=10bc0144-84ef-4d47-b960-096937292131 | trans=10bc0144-84ef-4d47-b960-096937292131 | op=IoTAgentNGSI.DomainControl | srv=n/a | subsrv=n/a | msg={ TypeError: Cannot read property 'statusCode' of undefined
> at Request._callback (/opt/iotajson/lib/bindings/HTTPBinding.js:126:67)
> at self.callback (/opt/iotajson/node_modules/request/request.js:185:22)
> at emitOne (events.js:116:13)
> at Request.emit (events.js:211:7)
> at Request.onRequestError (/opt/iotajson/node_modules/request/request.js:881:8)
> at emitOne (events.js:116:13)
> at ClientRequest.emit (events.js:211:7)
> at Socket.socketErrorListener (_http_client.js:401:9)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at emitErrorNT (internal/streams/destroy.js:66:8)
> at _combinedTickCallback (internal/process/next_tick.js:139:11)
> at process._tickDomainCallback (internal/process/next_tick.js:219:9)
> domain:
> Domain {
> domain: null,
> _events: { error: [Function: domainErrorHandler] },
> _eventsCount: 1,
> _maxListeners: undefined,
> members: [ [Object] ],
> start: 1568118873386,
> trans: '10bc0144-84ef-4d47-b960-096937292131',
> corr: '10bc0144-84ef-4d47-b960-096937292131',
> op: 'IoTAgentNGSI.MongoDBGroupRegister' },
> domainThrown: true } | comp=IoTAgent

**Comment by fgalan** [comment]
This issue has been closed. Should I understand you finally solved the problem? Could you include some information about what the solution was, please? That information can be useful for other people in the community using the component.

Thanks!
