### ISSUE TITLE
Review documentation related with new MQTT topic prefix

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#451]
Since PR https://github.com/telefonicaid/iotagent-json/pull/450 IOTA-JSON uses `/json` as topipc prefix. Although the all way (i.e. without prefix) is still supported due to backward compability we are going to recommend this new usage. Thus, documentation need to be reviewed and changed.

**Comment by AlvaroVega** [comment]
fixed in https://github.com/telefonicaid/iotagent-json/pull/450
