### ISSUE TITLE
Question: Interfacing with external mqtt brokers

### ISSUE THREAD

**Issue by ilarimikkonen** [telefonicaid/iotagent-json#461]
Hi,

I'm have been testing the iotagent-json with mqtt. Is there any way to interface with external mqtt broker? 

Say we have a broker in <IPxxyy>:1883 that publishes sensor information on topic tree like /this/that/+/those/+ 

Is there any way of subscribing to that topic? It seems that IOTA assumes /{{api-key}}/{{device-id}}/attrs per documentation.

**Comment by ilarimikkonen** [comment]
to add a detail: the broker is not running on the same server, it's not under our control. External domain.

**Comment by ilarimikkonen** [comment]
hello, any ideas on this?

**Comment by fgalan** [comment]
You have some degree of configuration for MQTT transport (see https://github.com/telefonicaid/iotagent-json/blob/master/docs/installationguide.md#mqtt-configuration). You can set for instance the broker to which the IOTA connects, but, as far as I know, the topic is not configurable.

Maybe some other (@AlvaroVega @jason-fox ) could confirm.

**Comment by jason-fox** [comment]
With the MQTT transport, the topic path is used to identify the device via the deviceId and API key - compare the following:

* HTTP: https://github.com/Fiware/tutorials.IoT-Agent/#four-request
* MQTT https://github.com/FIWARE/tutorials.IoT-over-MQTT#four-mqtt-request

The MQTT tutorial shows an example of how to subscribe to a topic. You could create a simple service which listens to  `/this/that/*`, interprets the `deviceId` from the message or topic path and reposts to `/<apikey>/<deviceId>/attrs` - potentially to **another** MQTT broker instance listening on another port.


```javascript
const mqtt = require('mqtt');

const mqttBrokerUrl = process.env.MQTT_BROKER_URL || 'mqtt://mosquitto';
const apiKey = process.env.DUMMY_DEVICES_API_KEY || '1234';
const topics = '/' + apiKey + '/#';

mqttClient = mqtt.connect(mqttBrokerUrl);
mqttClient.on('connect', () => {
    mqttClient.subscribe(topics);
    mqttClient.subscribe(topics + '/#');
});

mqtt.connect(mqttBrokerUrl);
```

```javascript
sendAsMQTT(deviceId, apiKey, state) {
    const topic = '/' + apiKey + '/' + deviceId + '/attrs';
    mqttClient.publish(topic, state);
}
```

**Comment by ilarimikkonen** [comment]
Thanks guys, I suspected as much. So the options are: 1) run a proxying component / broker 2) Modify source code (we are not going to do this). We also tested Apache Nifi as a solution, but that is bit on the heavy side.

**Comment by fgalan** [comment]
We're welcome!

If you find your doubts answered, I'd suggest to close this issue, please. Thanks!
