### ISSUE TITLE
Add: Multimeasure support (MQTT and AMQP transports)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#462]
(It comes from https://github.com/telefonicaid/iotagent-json/pull/391)

Multimeasures has been implemented for HTTP transport. What is pending is to implement multimeasures for MQTT and AMPQ transports (and modify the "IMPORTANT NOTE" mark in documentation accordingly)

**Comment by Chandradeep-NEC** [comment]
@fgalan 
Now We have started working on this issue.

**Comment by Chandradeep-NEC** [comment]
@fgalan 
I've raised PR #498 for this issue. Kindly merge the PR in master branch if there is no issue.

**Comment by fgalan** [comment]
Once PR #498 has been merged I understand this issue can be closed.
