### ISSUE TITLE
MQTT Client ID should be configurable

### ISSUE THREAD

**Issue by rg2011** [telefonicaid/iotagent-json#466]
Some MQTT brokers (e.g. https://myqtthub.com/) restrict connections based on client id, not only username & password.

The MQTT library used by this IoTAgent supports specifying the client id (https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options). Accepting the client ID as a parameter would allow this IoTAgent to be used with such brokers.

**Comment by AlvaroVega** [comment]
According with https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options default client id used is: 

clientId: 'mqttjs_' + Math.random().toString(16).substr(2, 8)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/562
