### ISSUE TITLE
Server Drop after reboot

### ISSUE THREAD

**Issue by ssavva05** [telefonicaid/iotagent-json#480]
I install iot-agent-json in a CentOS 7 guest OS (in a VM). The service works Initially. Then, when I restart the Guest OS and try to start the service again I manage to do only one request and then the service drop.  To make it work again i have to do npm uninstall and npm install again. Why is this happen ? Is there any file that I have to delete at reboot?

**Comment by fgalan** [comment]
Thanks for the report!

So you mean that request kills the IOTA process after the reboot?

**Comment by ssavva05** [comment]
Yes, After the reboot I run again the nohup bin/iotagent-json &> /var/log/iotAgent& and after the service receive one request, it kills the IOTA process. And get exit status 127  in process.

**Comment by fgalan** [comment]
Can you provide the full log? Maybe we can find some piece of useful information about the problem in it...

**Comment by ssavva05** [comment]
Hello, 
  I didn't find anything unusual in the log file, but I am find out what is happened! I have to disable the firewall-cmd in centos and give appropriate permissions in the logs folder again. Science then, everything working as expected . Thank you very much!

**Comment by fgalan** [comment]
Happy to know you finally solved! :)

Just curiosity... what was the cause of the problem? A too much aggressive firewall killing the process (never has seen that before ;)?

**Comment by fgalan** [comment]
(If the problem has been solved, please close the issue. Thanks!)

**Comment by ssavva05** [comment]
Yes, this is very strange! Now everything is fine. Thanks a lot!
