### ISSUE TITLE
Error processing 0.0 messages

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-json#486]
At function parseMessage

https://github.com/telefonicaid/iotagent-json/blob/449e3a2b05bb9f0dd452bf0be18f10be48f7c613/lib/commonBindings.js#L46

there is a problem determining the MEASURES 3 condition

Take into account that:
> JSON.parse('0')
0

is falsy.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/487
