### ISSUE TITLE
Client Id in MQTT Broker options  IoT Agent

### ISSUE THREAD

**Issue by achandana** [telefonicaid/iotagent-json#497]
We are using VerneMQ as MQTT broker and enabled the DB authentication for VerneMQ. For DB authentication we should have the client id in DB along with username and password. 

I have customized the IoT agent by adding Client Id in MQTT connections option as below.

 const options = {
        protocol: mqttConfig.protocol ? mqttConfig.protocol : 'mqtt',
        host: mqttConfig.host ? mqttConfig.host : 'localhost',
        port: mqttConfig.port ? mqttConfig.port : 1883,
        key: mqttConfig.key ? fs.readFileSync(mqttConfig.key, 'utf8') : null,
        ca: mqttConfig.ca ? fs.readFileSync(mqttConfig.ca, 'utf8') : null,
        cert: mqttConfig.cert ? fs.readFileSync(mqttConfig.cert, 'utf8') : null,
        rejectUnauthorized,
        username: mqttConfig.username ? mqttConfig.username : null,
        password: mqttConfig.password ? mqttConfig.password : null,
        keepalive: mqttConfig.keepalive ? parseInt(mqttConfig.keepalive) : 0,
        connectTimeout: 60 * 60 * 1000,
        **clean: false,
        clientId: 'iotagent'**
    };

 IoT agent is connected to Vernemq but when we send the data to IoT agent its not reaching to IoT agent. Could anyone please help on this issue.

**Comment by fgalan** [comment]
Can you provide the link to the IOTA-JSON or IOTA Node Lib documentation about the "clean" and "clientId" options you are trying to use?

I have had a look to MQTT-related options at https://github.com/telefonicaid/iotagent-json/blob/master/docs/installationguide.md#mqtt-configuration and I haven't found anything about them...

**Comment by onrao** [comment]
@fgalan 
Dear Galan we had done changes in iotagent json to o support the most of the mqtt brokers (as per the MQTT specification)to enabled secured AuthN and AuthZ recommend clientid,username and password .
However,here we had observed two issues if we enable clientID as static 
1.If the broker goes down and comesup then iotagent couldn't connect with it automatically.
2. Dataloss observed even after reconnecting with iotagent restart.

We would like to understand and seeking a solution
 How to enable secure AuthN and AuthZ for this iotagent client at attached broker level ?
Scaling IoTagent  JSON for mqtt in cloud?
Please quickly provide comment o these queries as we are blocked with this issue.

**Comment by fgalan** [comment]
@onrao by clientID I understand you mean the clientID functionality described at https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md#configuration and related with Oauth2 autentication. Is my understanding correct?

**Comment by fgalan** [comment]
Fixed by https://github.com/telefonicaid/iotagent-json/pull/562

This issue could be closed but, before doing that, it would be great if @achandana and/or @onrao could provided feedback about the implemented solution, pls. Use `:latest` at dockerhub after waiting some time (the PR has been just merged and dockerhub may take a bit to build the new container).
