### ISSUE TITLE
README doesn't mention which version of the context broker this agent is for

### ISSUE THREAD

**Issue by hspaay** [telefonicaid/iotagent-json#499]
There are now 3 context broker versions, v1, v2 and LD. It looks like this agent is for v2 but it would be helpful to mention in the README which version of the context broker this is for.
Thank you

**Comment by fgalan** [comment]
IOTA-JSON (and any other IOTA based in the [iotagent-node-lib](https://github.com/telefonicaid/iotagent-node-lib)) uses NGSIv2 as default. It allows also NGSIv1 (setting `contextBorker.ngsiVersion` to `v1`, see https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md#global-configuration) althought we strongly discourange doing so, as NGSIv1 is deprecated.

An [experimenta branch](https://github.com/telefonicaid/iotagent-node-lib/pull/849) develops NGSI-LD in iotagent-node-lib. You could use that branch is you set that dependency in IOTA-JSON packages.json (as soon [here](https://github.com/telefonicaid/iotagent-json/pull/469/files)) and you could set `contextBroker.ngsiVersion` to `ld`.

**Comment by hspaay** [comment]
Thank you for the clarification @fgalan. This fully answers my question and the next question I was going to have :+1:
