### ISSUE TITLE
retain(mqtt) should be configured at device(command) level, not only agent

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#504]
Some other changes are expected https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/createDevice.json#L150

**Comment by AlvaroVega** [comment]
Should include `mqtt { retain, qos}` not only `retain`

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/507 (in this IOTA) and https://github.com/telefonicaid/iotagent-ul/pull/448 (in IOTA-UL).
