### ISSUE TITLE
Different service/subservice for same topics in "Device not found for topic" warning logs

### ISSUE THREAD

**Issue by smartcitydevops** [telefonicaid/iotagent-json#587]
Related to https://github.com/telefonicaid/iotagent-json/issues/374 we are anayzing logs in order to check possible devices that would need the recommended prefix in that 374 issue

But we have noticed that there are different service-subservice warn logs for the same device-topic in the same day. A small example

time=2021-08-18T04:07:57.467Z | lvl=WARN | corr=6b050c69-573b-48a1-b26d-ebe4093ed3ef | trans=6b050c69-573b-48a1-b26d-ebe4093ed3ef | op=IoTAgentJSON.commonBinding | from=n/a | srv=service1| subsrv=/subservice1| msg=MEASURES-004: Device not found for topic [/q8obzuly1cfl7c1uqephdqjuf/device:wt:13@0080000004029083/attrs] | comp=IoTAgent

time=2021-08-18T03:52:54.692Z | lvl=WARN | corr=955d0110-65f0-4297-ab20-edf8a3aac8c2 | trans=955d0110-65f0-4297-ab20-edf8a3aac8c2 | op=IoTAgentJSON.commonBinding | from=n/a | srv=service2| subsrv=/subservice2| msg=MEASURES-004: Device not found for topic [/q8obzuly1cfl7c1uqephdqjuf/device:wt:13@0080000004029083/attrs] | comp=IoTAgent

In fact, we have found 5 different services- subservices for the same aforementioned device -topic in the last 24 hours. And we cannot rely on selecting the service-subservice with the highest frequency, as we have reported the data of the device-topic to the person in charge of the service-subservice and he reported that this device was not in his device inventory.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/591
