### ISSUE TITLE
Edit device by adding endpint does not convert device from pooling  to push 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#602]
When a device with a command is provisioned like: (for pooling model)
```
{
"devices": [{
"device_id": "test27",
"protocol": "IoTA-JSON",
"entity_name": "test27",
"entity_type": "thing",
"transport":"HTTP",
"commands": [{
"name": "ping",
"type": "command"
}]
}]
}
```

and later is updated adding (for being push model)
```
"endpoint": "http://enf093fez2nfk.x.pipedream.net",
```

internal `pooling` device property is not updated to false, appearing in true

Similar bug is present in iotagent-ul

**Comment by AlvaroVega** [comment]
At provision time that check is performed by 
https://github.com/telefonicaid/iotagent-json/blob/3f41bd393ac10efa7b8501d5534d077e3daf9353/lib/bindings/HTTPBinding.js#L390-L404

**Comment by AlvaroVega** [comment]
Unfortunately there is not an equivalent handler for update device in iotagent-node-lib

**Comment by AlvaroVega** [comment]
In the mean time the workaround is delete that device and create again that device with proper endpoint value

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/603
