### ISSUE TITLE
jexl in commands

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#634]
Allow perform jexl/expressions transformations in commands

Not sure if this issue should be here or in agents

**Comment by fgalan** [comment]
Seems to be a common functionality... maybe i'ts better in the iotagent-node-lib repository (use "Transfer issue" button)

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-json/pull/635
