### ISSUE TITLE
bad mqtt measure is progresing as a multiple measure after be procesed as hex string

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#642]
mosquitto_pub -h localhost -t /json/<apikey>/<id_disp>/attrs -m 'bullshit' 

time=2022-03-25T09:34:29.521Z | lvl=DEBUG | corr=86de3fd2-4f67-4ec8-8351-1b8b74142661 | trans=86de3fd2-4f67-4ec8-8351-1b8b74142661 | op=IoTAgentJSON.commonBinding | from=n/a | srv=n/a | subsrv=n/a | msg=message topic: /json/<apikey>/<id_disp>/attrs | comp=IoTAgent
time=2022-03-25T09:34:29.521Z | lvl=DEBUG | corr=86de3fd2-4f67-4ec8-8351-1b8b74142661 | trans=86de3fd2-4f67-4ec8-8351-1b8b74142661 | op=IoTAgentJSON.commonBinding | from=n/a | srv=n/a | subsrv=n/a | msg=stringMessage: [mierda] parsedMessage: [6d6965726461] | comp=IoTAgent
time=2022-03-25T09:34:29.521Z | lvl=DEBUG | corr=86de3fd2-4f67-4ec8-8351-1b8b74142661 | trans=86de3fd2-4f67-4ec8-8351-1b8b74142661 | op=IoTAgentJSON.commonBinding | from=n/a | srv=n/a | subsrv=n/a | msg=parserMessage array: [ '6d6965726461' ] | comp=IoTAgent

time=2022-03-25T09:34:29.532Z | lvl=DEBUG | corr=0d51f136-eb0f-4a71-acb4-915f665e8b43 | trans=0d51f136-eb0f-4a71-acb4-915f665e8b43 | op=IoTAgentNGSI.NGSIService | from=n/a | srv=smartcity | subsrv=/ | msg=executeWithDeviceInfo entityName mientity type thing1 apikey  attributes [{"name":"0","type":"string","value":"6"},{"name":"1","type":"string","value":"d"},{"name":"2","type":"string","value":"6"},{"name":"3","type":"string","value":"9"},{"name":"4","type":"string","value":"6"},{"name":"5","type":"string","value":"5"},{"name":"6","type":"string","value":"7"},{"name":"7","type":"string","value":"2"},{"name":"8","type":"string","value":"6"},{"name":"9","type":"string","value":"4"},{"name":"10","type":"string","value":"6"},{"name":"11","type":"string","value":"1"}] deviceInformation {"_id":"623b2d57718718157f8b155c","commands":[{"name":"command1","type":"command","value":"","object_id":"command1"}],"staticAttributes":[],"subscriptions":[],"creationDate":"2022-03-23T14:23:19.432Z","id":"disp1","type":"thing1","name":"mientity","service":"smartcity","subservice":"/","registrationId":"623b2d57d6528456f13f42b0","internalId":null,"apikey":"<apikey>","protocol":"IoTA-JSON","transport":"HTTP","polling":true,"timestamp":true,"explicitAttrs":false,"lazy":null,"active":[]} | comp=IoTAgent

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-json/pull/643
