### ISSUE TITLE
sending mqtt command and default mqtt options is causing a (infinite?) loop of reconections

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#650]
with default mqtt options like:
kepalive = 60
retries = 5
retryTime = 5

Workaround:  use keepalive = 0

**Comment by AlvaroVega** [comment]
time=2022-04-05T10:55:06.143Z | lvl=INFO | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=MQTT Client connected | comp=IoTAgent
time=2022-04-05T10:55:06.143Z | lvl=DEBUG | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Recreating subscriptions for all devices | comp=IoTAgent
time=2022-04-05T10:55:06.143Z | lvl=DEBUG | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Generating topics | comp=IoTAgent
time=2022-04-05T10:55:06.143Z | lvl=DEBUG | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Subscribing to topics: ["$share/json//+/+/attrs/+","$share/json//json/+/+/attrs/+","$share/json//+/+/attrs","$share/json//json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json//json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json//json/+/+/cmdexe","$share/json//+/+/attrs/+","$share/json/json/+/+/attrs/+","$share/json//+/+/attrs","$share/json/json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json/json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json/json/+/+/cmdexe"] | comp=IoTAgent
time=2022-04-05T10:55:06.144Z | lvl=INFO | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Successfully subscribed to the following topics:
["$share/json//+/+/attrs/+","$share/json//json/+/+/attrs/+","$share/json//+/+/attrs","$share/json//json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json//json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json//json/+/+/cmdexe","$share/json//+/+/attrs/+","$share/json/json/+/+/attrs/+","$share/json//+/+/attrs","$share/json/json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json/json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json/json/+/+/cmdexe"]
 | comp=IoTAgent
time=2022-04-05T10:55:07.036Z | lvl=INFO | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=MQTT Client connected | comp=IoTAgent
time=2022-04-05T10:55:07.036Z | lvl=DEBUG | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Recreating subscriptions for all devices | comp=IoTAgent
time=2022-04-05T10:55:07.036Z | lvl=DEBUG | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Generating topics | comp=IoTAgent
time=2022-04-05T10:55:07.036Z | lvl=DEBUG | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Subscribing to topics: ["$share/json//+/+/attrs/+","$share/json//json/+/+/attrs/+","$share/json//+/+/attrs","$share/json//json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json//json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json//json/+/+/cmdexe","$share/json//+/+/attrs/+","$share/json/json/+/+/attrs/+","$share/json//+/+/attrs","$share/json/json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json/json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json/json/+/+/cmdexe"] | comp=IoTAgent
time=2022-04-05T10:55:07.036Z | lvl=INFO | corr=1e91e18c-23fb-4c85-ace4-c689e864756d | trans=1e91e18c-23fb-4c85-ace4-c689e864756d | op=IOTAJSON.MQTT.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=Successfully subscribed to the following topics:
["$share/json//+/+/attrs/+","$share/json//json/+/+/attrs/+","$share/json//+/+/attrs","$share/json//json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json//json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json//json/+/+/cmdexe","$share/json//+/+/attrs/+","$share/json/json/+/+/attrs/+","$share/json//+/+/attrs","$share/json/json/+/+/attrs","$share/json//+/+/configuration/commands","$share/json/json/+/+/configuration/commands","$share/json//+/+/cmdexe","$share/json/json/+/+/cmdexe"]
 | comp=IoTAgent

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/651
