### ISSUE TITLE
Support for full binary frames in HTTP transport

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#661]
POST  <endpoint>/iot/json?k=<apikey>&i=<deviceId>&attrs=dataframe

Content-type: text/plain

And maybe this could also works:
curl -i -X POST 'http://localhost:7897/iot/json?i=disp4&k=6idn7z9cba3o57tgoascazdwd?attrs=myattr1' -d '33' -H 'content-type: application/json'

**Comment by AlvaroVega** [comment]
Finally path for single measures will be /iot/json/attrs/<attrValue> to keep aligned with MQTT path for incoming measures (`/json/<apikey>/attrs/`)

**Comment by fgalan** [comment]
Once PR https://github.com/telefonicaid/iotagent-json/pull/667 has been merded, should this issue be closed?
