### ISSUE TITLE
Useless code in HTTPBinding

### ISSUE THREAD

**Issue by Manuel-Pi** [telefonicaid/iotagent-json#663]
Hi, 

This is not really an issue, but I think the **addTimestamp** function in **HTTPBinding.js** is useless. Nothing is used outside the scope of the function.

```javascript
function addTimestamp(req, res, next) {
    const arr = req.jsonPayload;
    let timeStampData;
    const dataWithTimeStampArr = [];
    for (const i in arr) {
        if (req.query.t && arr[i]) {
            timeStampData = arr[i];
            timeStampData[constants.TIMESTAMP_ATTRIBUTE] = req.query.t;
            dataWithTimeStampArr.push(timeStampData);
        }
    }
    next();
}
```

Maybe I'm missing something!

**Comment by AlvaroVega** [comment]
Hi,
I guess is referenced from:
https://github.com/telefonicaid/iotagent-json/blob/504815fa9a42c38893ab0bd63c0b5cd032c38173/lib/bindings/HTTPBinding.js#L554-L561
https://github.com/telefonicaid/iotagent-json/blob/504815fa9a42c38893ab0bd63c0b5cd032c38173/lib/bindings/HTTPBinding.js#L563-L571
https://github.com/telefonicaid/iotagent-json/blob/504815fa9a42c38893ab0bd63c0b5cd032c38173/lib/bindings/HTTPBinding.js#L573-L582
isn't it?

**Comment by Manuel-Pi** [comment]
Yes this function is called but it does nothing!

**Comment by AlvaroVega** [comment]
You're right! 
Could you try to do a PR to remove that code?
Thanks in advance!

**Comment by Emmanuel-Nau** [comment]
For sure! 
https://github.com/telefonicaid/iotagent-json/pull/666
