### ISSUE TITLE
Missing notificationHandler for MQTT-Binding for bidirectional attribute

### ISSUE THREAD

**Issue by Blobonat** [telefonicaid/iotagent-json#691]
In the documentation for the [MQTT-Binding ](https://github.com/telefonicaid/iotagent-json/blob/master/docs/usermanual.md#mqtt-binding) it is stated
> The latest versions of the Provisioning API allow for the definition of reverse expressions to keep data shared between the Context Broker and the device in sync (regardless of whether the data originated in plain data from the device or in a transformation expression in the IoTAgent). In this cases, when a reverse expression is defined, whenever the bidirectional attribute is modified, the IoTAgent sends a command to the original device, with the name defined in the reverse expression attribute and the ID of the device (see Commands Syntax, just above).

But only a notificationHandler for the HTTP-Binding is currently defined. Is this a missing feature or an error in the documentation?

**Comment by mapedraza** [comment]
the `notificationHandler` is only used in this part of the code:
https://github.com/telefonicaid/iotagent-json/blob/5a70f661b5c6451d896d2697a00f99f6a187c4c5/lib/iotagent-json.js#L85-L92

Which is related with the [bidirectional plugin](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/advanced-topics.md#bidirectionality-plugin-bidirectional). Expressions on commands are available both for MQTT and HTTP transports.

**Comment by Blobonat** [comment]
The [MQTT-Binding](https://github.com/telefonicaid/iotagent-json/blob/5a70f661b5c6451d896d2697a00f99f6a187c4c5/lib/bindings/MQTTBinding.js#L425) currently does not implement a `notificationHandler` whereas the [HTTP-Binding](https://github.com/telefonicaid/iotagent-json/blob/5a70f661b5c6451d896d2697a00f99f6a187c4c5/lib/bindings/HTTPBinding.js#L719) supports a `notificationHandler`. Therefore I think the bidirectional plugin currently only works with a HTTP Transport Protocol. From the above mentioned documentation this was not clear to me.

**Comment by mapedraza** [comment]
Probably this feature was introduced first in HTTP but never got implemented in MQTT. 

If you are interested in having this using MQTT, I suggest you to open a PR adding this new functionality. In the case of MQTT, is even easier than HTTP (just pushing the data to the broker, no need to handle polling notifications).

Probably this part of the code can be easily adapted and included in the MQTT-Biding:

https://github.com/telefonicaid/iotagent-json/blob/5a70f661b5c6451d896d2697a00f99f6a187c4c5/lib/bindings/HTTPBinding.js#L690-L696

**Comment by MayankSingh-NEC** [comment]
Hi @Blobonat and @mapedraza, I'm interested to work on this issue.

I've tried to reproduce this issue but I found that the function ("notificationHandler()") is not getting call.
Below steps, I've followed:
1. Service Provisioning
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Bell",
     "resource":    "/iot/json"
   }
 ]
}'

2. Device Provisioning
curl -L -X POST 'http://localhost:4041/iot/devices' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
-H 'Cookie: _csrf=MAPTGFPcoPnewsGCWklHi4Mq' \
--data-raw '{
  "devices": [
    {
      "device_id": "bell001",
      "entity_name": "urn:ngsi-ld:Bell:001",
      "entity_type": "Bell",
      "protocol": "PDI-IoTA-Json",
      "transport": "HTTP",
      "endpoint": "http://iot-sensors:3001/iot/bell001",
      "attributes": [
          {
          "name":"ring",
          "type":"Text",
          "expression": "{@ring}",
          "reverse": [
            {
              "object_id":"ring",
              "type": "Text",
              "expression": "{@ring}"
            }
          ]
        }
      ],
       "static_attributes": [
         {"name":"refStore", "type": "Relationship","value": "urn:ngsi-ld:Store:001"}
        ]
    }
  ]
}'

3. Request:
curl -iX POST \
  http://localhost:4041/v2/op/update \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
    "actionType": "update",
    "entities": [
        {
            "type": "Bell",
            "id": "urn:ngsi-ld:Bell:001",
            "ring" : {
                "type": "command",
                "value": ""
            }
        }
    ]
}'

4. Enable CB:
curl -iX PATCH \
  'http://localhost:1026/v2/entities/urn:ngsi-ld:Bell:001/attrs' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "ring": {
      "type" : "command",
      "value" : ""
  }
}'
 
Could you help me with more detail steps.

**Comment by fgalan** [comment]
@MayankSingh-NEC thanks you for your willingness to work on this issue

However, currently were are working in a hard refactor of the IOTA Lib (PR https://github.com/telefonicaid/iotagent-node-lib/pull/1314) and it would be better to hold on a bit (until the refactor finished) to start working on it.

**Comment by mapedraza** [comment]
@MayankSingh-NEC the hard IOTA refactor that @fgalan mentioned above is concluded. 

The strategy for this issue should be:
1. Test if bidirectionality actually works with MQTT protocol. As I can see in the examples you did, the transport protocolo selected is HTTP, so it is not valid. Maybe implementing a test using MQTT should be a good idea (consider this as base: https://github.com/telefonicaid/iotagent-json/blob/master/test/unit/ngsiv2/bidirectionalityHttp-test.js) 
2. Implement MQTT `notificationHandler`if needed to add bidirectionality support to MQTT 

@Blobonat Could you confirm this plan resolves the issue? 

@MayankSingh-NEC Meanwhile, test can be implemented
