### ISSUE TITLE
Subscribe to a specific MQTT topic

### ISSUE THREAD

**Issue by NunopRolo** [telefonicaid/iotagent-json#711]
Hello
I have a sensor that sends data by MQTT on a specific topic that it is not possible to change. Topic looks like this: `device_type/device_id/phase/power`

How can I configure this topic in Fiware IOT Agent? 
From what I understand from the IOT Agent documentation, the MQTT topic is something like this: `apikey/device_id/power/attrs`, but I haven't found anything on how to set up a customizable MQTT topic.

Thank you!

**Comment by mapedraza** [comment]
The IoT Agent specification defines the topic in which is expected to receive the data. This is something that defines the IoT Agent behaviour (you can't change verbs and routes on an external REST API, just consume it).

Being said this, there is a MQTT Broker functionality that allows to synchronise data between two different topics (either different brokers, or the same). This functionality is called [MQTT Bridging](https://www.google.com/search?q=mqtt+bridging+topics). This probably could solve your scenario
