### ISSUE TITLE
No plain text command return option

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-json#716]
When returning a command after an expression, probably is interesting to return a plain text string like:

```
hi
```

Unfortunately, the only option available to return non binary data is `json` (default case). Since this option executes:

```js 
serialized = JSON.stringify(payload);
```

Strings will always have the quotes `"`, so it is not possible to return something like `hi`, obtaining `"hi"`.

Adding a new option (I.E: `text`) that return the value without calling `JSON.stringfy` could solve this issue. See the following code block:

```js
...
   case 'binaryfromjson': // used by AMQP transport 
                 serialized = Buffer.from(JSON.stringify(payload)); 
                 break; 
   case 'text': // prevent quotes 
                 serialized = payload;
                 break; 
   case 'json': // passthrough 
   default: 
                 serialized = JSON.stringify(payload); 
 ...
```

Code related:
https://github.com/telefonicaid/iotagent-json/blob/07ec3b1e2ac64f156f498eaaf8abc5cdf05c9cf1/lib/commandHandler.js#L41-L62

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/720
