### ISSUE TITLE
iotagent- json should be used in place of iotagent-ul in commandsPolling-test.js

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/iotagent-json#726]
In file: https://github.com/telefonicaid/iotagent-json/blob/master/test/unit/ngsiv2/commandsPolling-test.js iotagent-ul is used multiple times. It should be iotagent-json.

**Comment by Keshav-NEC** [comment]
Hi, I am working on the issue

**Comment by fgalan** [comment]
Fixed by PR #727
