### ISSUE TITLE
iotaJsonTester.js is missing from the repository

### ISSUE THREAD

**Issue by NedKelly07** [telefonicaid/iotagent-json#774]
### IoT Agent JSON version the issue has been seen with

2.2.0

### Bound or port used (API interaction)

Other

### NGSI version

NGSIv2

### Are you running a container?

None

### Image type

None

### Expected behaviour you didn't see

In the README.md file, there is a section that says there is a file to help with testing the IoT agent in bin/iotaJsonTester.js.

no such a file exists in the repository. I cant find it anywhere.

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4041"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-json"
    - "IOTA_HTTP_PORT=7896"
    - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by fgalan** [comment]
Thank for your feedback!

PR https://github.com/telefonicaid/iotagent-json/pull/775 removes that reference.

Please close issue if you find this is ok.

**Comment by NedKelly07** [comment]
The actual file would be verry usefull to me. has it been depreciated? can I find it anywhere

**Comment by mapedraza** [comment]
You can find the script in previous commits/versions. I.E:
https://github.com/telefonicaid/iotagent-json/blob/aef8f204e97e7052afbb1c4bc2eb08adada7fc7a/bin/iotaJsonTester.js
