### ISSUE TITLE
constants.DEFAULT_ATTRIBUTE_TYPE is string instead of Text

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#810]
### Component

Techdeb

### Is your feature request related to a problem? Please describe

Used by
https://github.com/telefonicaid/iotagent-json/blob/715fa0389a655214cc264778e13571f306ae12d4/lib/commonBindings.js#L81-L99

### Describe the solution you'd like

It should be Text, which is the default type for NGSI

**Comment by fgalan** [comment]
> It should be Text, which is the default type for NGSI

Ref: https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/orion-api.md#partial-representations

**Comment by Keshav-NEC** [comment]
Hi @fgalan @AlvaroVega, I would like to contribute on this issue.

**Comment by fgalan** [comment]
Fixed by PR #813
