### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by KeshavSoni2511** [telefonicaid/iotagent-json#830]
I have found broken link at:
https://github.com/telefonicaid/iotagent-json/blob/66296eef1431093b0c71f22f1b96f110db86dd00/README.md?plain=1#L36

**Comment by fgalan** [comment]
After merging PR https://github.com/telefonicaid/iotagent-json/pull/831, should this issue be closed?

**Comment by KeshavSoni2511** [comment]
Hi @fgalan, yes this issue can be closed.
