### ISSUE TITLE
modify apikey in a provisioned device

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#833]
### IoT Agent JSON version the issue has been seen with

3.4.0

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

None

### Expected behaviour you didn't see

modify apikey in a provisioned device

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4041"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-json"
    - "IOTA_HTTP_PORT=7896"
    - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by Madhu1029** [comment]
Hi @AlvaroVega ,

The bug is to provide a functionality to update apikey of a pre-provisioned device.

**For Example:** A device is provisioned with apikey '123'. Then one should able to change the apikey from '123' to '456' with update API of device provisioning.

Could you please confirm the above understanding of issue?

**Comment by fgalan** [comment]
Your understanding is right.

**Comment by AlvaroVega** [comment]
> Hi @AlvaroVega ,
> 
> The bug is to provide a functionality to update apikey of a pre-provisioned device.
> 
> **For Example:** A device is provisioned with apikey '123'. Then one should able to change the apikey from '123' to '456' with update API of device provisioning.
> 
> Could you please confirm the above understanding of issue?

BTW I'm working on this issue

**Comment by Madhu1029** [comment]
> BTW I'm working on this issue

Thanks for the information.

**Comment by Madhu1029** [comment]
Hi @fgalan ,

As mentioned @AlvaroVega is working on this issue. Please confirm if I should work on this issue or he will continue to work.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1616 + PR #834  + PR https://github.com/telefonicaid/iotagent-ul/pull/678
