### ISSUE TITLE
querying devices by static attributes

### ISSUE THREAD

**Issue by butteronarchbtw** [telefonicaid/iotagent-json#835]
### IoT Agent JSON version the issue has been seen with

everything above 1.26.0

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

normal

### Expected behaviour you didn't see

After provisioning a device and service I expected them to be created as a context broker entity (as stated in the FIWARE tutorial) in order to query them by static attributes like other entities e.g. `?q=owner=="User1"` or `?type=Sensor`. This behaviour is crucial for my application and I found no documentation where this feature has gone since version 1.26.0. I saw something similar mentioned in #832 but for this specific feature there should exist an alternative.

### Unexpected behaviour you saw

Only measurements I send to the created device are listed as entities. When querying for a specific device or type that is not a type of a measurement, `[]` is returned.

### Steps to reproduce the problem

Create a service.
```sh
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    "/iot/d"
   }
 ]
}'
```

Create a device.
```sh
curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name": "count", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Store:001"}
     ]
   }
 ]
}
'
```

Do a query for the device, e.g. request the specific device entity
```sh
curl -G -X GET \
  'http://localhost:1026/v2/entities/urn:ngsi-ld:Motion:001' \
  -d 'type=Motion' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'
```

### Configs

```yaml
environment:
  - "IOTA_CB_HOST=orion"
  - "IOTA_CB_PORT=1026"
  - "IOTA_NORTH_PORT=4041"
  - "IOTA_REGISTRY_TYPE=mongodb"
  - "IOTA_MONGO_HOST=mongodb"
  - "IOTA_MONGO_PORT=27017"
  - "IOTA_MONGO_DB=iotagent-json"
  - "IOTA_HTTP_PORT=7896"
  - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by fgalan** [comment]
> After provisioning a device and service I expected them to be created as a context broker entity (as stated in the FIWARE tutorial) in order to query them by static attributes like other entities e.g. `?q=owner=="User1"` or `?type=Sensor`. This behaviour is crucial for my application and I found no documentation where this feature has gone since version 1.26.0. I saw something similar mentioned in #832 but for this specific feature there should exist an alternative.

The behaviour changed in IOTA-JSON 2.3.0, as explained [in this comment on the #832 issue you cite](https://github.com/telefonicaid/iotagent-json/issues/832#issuecomment-2149322180).

The entity associated to a given device is not created on device provisioning, but when the first device measure is received. Static attributes are included in that moment.

If you need static attributes in advance, you can pre-create the entity at CB using the NGSIv2 API, including the static attributes in that request.

(Removing "bug" label as this is not a bug but expected behaviour)

**Comment by fgalan** [comment]
With regards to documentation https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#config-groups

> Once a measure is received by the IoT Agent, the `apikey` and `resource` are used to identify the config group to which the device belongs. The config group is used to map the measure to a particular entity type and to provide the information needed to interact with the Context Broker.
> 
> If the device already exists in the Context Broker, the IoT Agent will update the entity with the new values. If the device does not exist, the IoT Agent will create it with the information provided by the config group **and eventually will also create the entity in the Context Broker**. This last operation is only possible if the IoT Agent is configured to use autoprovisioning.

https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#devices

> If devices are not pre-registered, they will be automatically created when a measure arrives to the IoT Agent - this process is known as autoprovisioning. The IoT Agent will create an empty device with the group apikey and type - the associated document created in database doesn't include config group parameters (in particular, timestamp, explicitAttrs, active or attributes, static and lazy attributes and commands). **The IoT Agent will also create the entity in the Context Broker if it does not exist yet.**

**Comment by butteronarchbtw** [comment]
Thanks for the thorough response!

There is one part that still did not work for me.

> The entity associated to a given device is not created on device provisioning, but when the first device measure is received. Static attributes are included in that moment.

As you can see when provisioning the device as follows,

```sh
curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name": "count", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Store:001"}
     ]
   }
 ]
}
'
```

the static attribute `refStore` gets added to that device. 

But when querying the CB for the device after adding a measurement as you described, it returns the following.

```json
[
	{
		"id": "Thing:motion001",
		"type": "Thing",
		"TimeInstant": {
			"type": "DateTime",
			"value": "2024-06-12T09:28:18.836Z",
			"metadata": {}
		},
		"c": {
			"type": "Text",
			"value": "1",
			"metadata": {
				"TimeInstant": {
					"type": "DateTime",
					"value": "2024-06-12T09:28:18.836Z"
				}
			}
		}
	}
]
```

Which does not include the `refStore` static attribute contrary to what you stated.

Is it me doing something wrong there?

**Comment by fgalan** [comment]
As far as I understand you have tested using ITOA-JSON 1.26.0 (please tell me otherwise).

I'd suggest to test with the newest IOTA-JSON version at the time of writing this (3.5.0) and tell us how it goes.

**Comment by butteronarchbtw** [comment]
Sorry, I forgot to specify what version I was using. Beforehand I was using version 3.3.0.

Now I've upgraded to the most recent version, being 3.5.0. I can confirm this by the following:

```sh
curl -X GET 'http://localhost:4041/iot/about'
```

Which yields me `{"libVersion":"4.5.0","port":"4041","baseRoot":"/","version":"3.5.0"}`, which should be right.

But I can still **not** confirm that static attributes are returned by the query, also with the commands @AlvaroVega posted.

The exact steps I took to reproduce my issue on version 3.5.0 were:

Creating a service

```sh
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    "/iot/json"
   }
 ]
}'
```

Creating a device - *note that `refStore` is a static attribute*

```sh
curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name": "count", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Store:001"}
     ]
   }
 ]
}
'
```

Sending a measurement

```sh
curl -iX POST \
  'http://localhost:7896/iot/json?k=4jggokgpepnvsb2uv4s40d59ov&i=motion001' \
  -H 'Content-Type: application/json' \
  -d '{"c": "1"}'
```

Querying the CB for the device

```sh
curl -X GET 'http://localhost:1026/v2/entities' -H 'fiware-service: openiot' -H 'fiware-servicepath: /'
```

Which leaves me with

```json
[
  {
    "id": "Thing:motion001",
    "type": "Thing",
    "TimeInstant": {
      "type": "DateTime",
      "value": "2024-06-12T12:47:21.741Z",
      "metadata": {}
    },
    "c": {
      "type": "Text",
      "value": "1",
      "metadata": {
        "TimeInstant": {
          "type": "DateTime",
          "value": "2024-06-12T12:47:21.741Z"
        }
      }
    }
  }
]
```

The response still does not contain `refStore`.

**Comment by AlvaroVega** [comment]
Why don't you include apikey in device at provisioning time? Otherwise only service (group) info about static attributes will be provisioned (since even entity_type is not the same for device and group)

**Comment by AlvaroVega** [comment]
@butteronarchbtw Why don't you include apikey in device at provisioning time? Otherwise only service (group) info about static attributes will be provisioned (since even entity_type is not the same for device and group)

**Comment by butteronarchbtw** [comment]
@AlvaroVega That was it! Either using the same `entity_type` for the device and service and/or using the `apikey` during provisioning solves the issue. Thank you!

But since these comments were taken straight from the docs [https://fiware-tutorials.readthedocs.io/en/latest/iot-agent-json.html](https://fiware-tutorials.readthedocs.io/en/latest/iot-agent-json.html), these should be updated I think. Is there a way I could contribute to this or are these handled internally?

**Comment by fgalan** [comment]
> But since these commands were taken straight from the docs https://fiware-tutorials.readthedocs.io/en/latest/iot-agent-json.html, these should be updated I think. Is there a way I could contribute to this or are these handled internally?

I think the maintainer of the tutorial documenation is @jason-fox . I understand he can tell you how to contribute to it.

In addition to that, if you find that the documentation of the iotagent-node-lib repository should be also improved based on your experience, please feel free to do a pull request with the contribution. We would be more than happy to review it and improve the IOTAs documentation :)

Apart from that, I understand this issue is solved and can be closed.
