### ISSUE TITLE
IoT Agent and Orion Connection:  [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated.

### ISSUE THREAD

**Issue by fadelcg** [telefonicaid/iotagent-json#838]
### IoT Agent JSON version the issue has been seen with

latest

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

None

### Unexpected behaviour you saw

I am trying to read  the IoT Device that I provide from the Context Broker:
![image](https://github.com/user-attachments/assets/39b3fe80-34b7-4b5c-82ba-fc74dcee6d13)

But the device cannot be found in the Context Broker.

When I try to trace the problem of Orion from the docker logs of the IoT Agent: This error comes up:

![image](https://github.com/user-attachments/assets/3153f718-b7e5-43f7-b160-921841a627b1)

### Steps to reproduce the problem

The service group creation is successfull:
![image](https://github.com/user-attachments/assets/ea392415-f845-4c57-9b6c-82bb67e65876)

The Provision of the devoce in the IoT Agent is also successfull:
![image](https://github.com/user-attachments/assets/19943919-5e6c-4c7d-8096-def7b4ad7618)

### Configs

This is the docker-compose file i am using:

volumes:
    mongodb: ~

services:
    iot-agent:
        image: fiware/iotagent-json:latest
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongodb
        expose:
            - "4041"
            - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_MONGO_HOST=mongodb"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-json"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_PROVIDER_URL=http://iot-agent:4041"

    mongodb:
        image: mongo:4.4
        hostname: mongodb
        container_name: db-mongo
        ports:
            - "27017:27017"
        command: --bind_ip_all
        volumes:
            - mongodb:/data

    orion:
        image: fiware/orion:latest
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongodb
        expose:
            - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongodb

### Log output

time=2024-07-19T19:27:58.817Z | lvl=DEBUG | corr=1ec9d5cc-93ec-4999-9f40-1fce9512965b | trans=1ec9d5cc-93ec-4999-9f40-1fce9512965b | op=IoTAgentNGSI.DeviceGroupService | from=n/a | srv=openiot | subsrv=/ | msg=validateGroup {"apikey":"4jggokgpepnvsb2uv4s40d59ov","cbroker":"
http://orion:1026","resource":"","type":"Thing","service":"openiot","subservice":"/"}
| comp=IoTAgent (node:1) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead. (Triggered by calling processImmediate on process.) (Use
node --trace-deprecation ...
to show where the warning was created)

Here below another logs when i run the docker with --trace deprecation:
{"op":"IoTAgentNGSI.JEXL","time":"2024-07-20T09:36:52.889Z","lvl":"INFO","msg":"Trasformations can be added to JEXL parser"}
(node:1) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead. (Triggered by calling emit on process.)
    at emitMakeCallbackDeprecation (node:domain:143:13)
    at process.topLevelDomainCallback (node:domain:157:5)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)

**Comment by fadelcg** [comment]
Solved: I changed the Docker Image version of the IoT Agent Json to 1.3.0 and it works. The Context Broker can now read the sensor i registered.

**Comment by fgalan** [comment]
Great to know you solved the issue!

However, note that IOTA JSON 1.3.0 is pretty old (released almost 8 years ago!). Newest version at the moment of writing this is IOTA-JSON 3.5.0.

**Comment by fadelcg** [comment]
Ok. Do you know how to solve this issue (**[DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead. (Triggered by calling emit on process.**) ? Thank you

**Comment by fgalan** [comment]
> Ok. Do you know how to solve this issue (**[DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead. (Triggered by calling emit on process.**) ? Thank you

Could you confirm that the version you are using is the lastest one (IOTA-JSON 3.5.0)? Are you getting that message with that version?

**Comment by fadelcg** [comment]
Yes I am using IOTA-JSON 3.5.0. The problem alsways raises everytime I create a service group:

![image](https://github.com/user-attachments/assets/a47ea4a2-bbd5-4241-8d8f-786b9dc478e4)

**Comment by fgalan** [comment]
Probably that needs some modifications in the IOTA JSON or IOTA Lib code. However, it's a minor issue, as it is just a deprecation warning.

@AlvaroVega what do you think?

**Comment by AlvaroVega** [comment]
https://private-user-images.githubusercontent.com/175042542/350533942-19943919-5e6c-4c7d-8096-def7b4ad7618.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDY3NjIsIm5iZiI6MTcyMjI0NjQ2MiwicGF0aCI6Ii8xNzUwNDI1NDIvMzUwNTMzOTQyLTE5OTQzOTE5LTVlNmMtNGM3ZC04MDk2LWRlZjdiNGFkNzYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwOTQ3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjhlZjM4M2UxN2I3ZDAwZDFmY2UyODBjZTk4YmQ1YTA1NDdlMjllNjk3MzFmNTUwNGM5MDI5ODEzNjk2ODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2q4Q8e4YjhzswvQZq0lx69MFS_wFbYK-zAdm_JkjP-Q

We encourage provide apikey at device provision.

**Comment by fadelcg** [comment]
I included now the apikey at device provision, but the context broker cannot still read the device. The response for entities-query is still empty.

**Comment by AlvaroVega** [comment]
> I included now the apikey at device provision, but the context broker cannot still read the device. The response for entities-query is still empty.

DId you send a mesaure to that device? Entity is not going to be created in CB until measure arrives to device.

**Comment by fadelcg** [comment]
Sorry I did not do that step. I thought it can be directly accessed by CB after the provision. Now it works. Thank you very much!
